### ISSUE TITLE
`emp destroy` does the 'type app name' check twice

### ISSUE THREAD

**Issue by Caleb-An** [remind101/empire#1047]
I don't know if this is intentional, but when you destroy an app with `emp destroy`, you have to type the app name twice (once b4 the commit message, once after the commit message). 

example with fake app foo: 
```
Calebs-MacBook-Pro:r101-api caleb$ emp-prod destroy foo
warning: This will destroy foo and its add-ons. Please type "foo" to continue:
> foo
A commit message is required, enter one below:
> destroying foo app
warning: This will destroy foo and its add-ons. Please type "foo" to continue:
> foo
Destroyed foo.
```

**Comment by ejholmes** [comment]
Oh yeah, I've ran into this before too. I think it's a symptom of how we require a commit message. For example, if you specify the commit message via the `-m` flag, you only get asked once. Annoying.
