### ISSUE TITLE
emp commands fail with protocol directive in ~/.netrc

### ISSUE THREAD

**Issue by bkolba** [remind101/empire#1056]
1. Set up an entry in `$HOME/.netrc` to look like this (the important part is the `protocol` directive):

```
machine github.com
  login <username>
  password <password>
  protocol https
```

2. `emp login`

Expected: prompted for credentials to login
Actual: `error: loading netrc: line 4: keyword expected; got protocol`

All `emp` commands will fail until the `protocol` directive is removed. Unclear how it was introduced in the first place but engineer on the team believes they simply followed Github's "cache your git credentials in osx keychain" guide

**Comment by ejholmes** [comment]
The closest thing to a grammar for the `.netrc` format I could find was from [netrc(5)](https://linux.die.net/man/5/netrc), which doesn't specify `protocol` as being recognized. Unfortunately, that document also doesn't say whether unrecognized keywords should be considered an error or ignored.

If the behavior of most other tools that read from `~/.netrc` is to ignore unrecognized keywords, then it seems like `emp` should do the same.

**Comment by ejholmes** [comment]
Did a little sleuthing. By chance, were they following this guide? http://bryanwweber.com/writing/personal/2016/01/01/how-to-set-up-an-encrypted-.netrc-file-with-gpg-for-github-2fa-access/

It looks like `protocol` might be specific to the [perl script it uses](https://raw.githubusercontent.com/git/git/master/contrib/credential/netrc/git-credential-netrc).

**Comment by bkolba** [comment]
Very possible. Feel free to close this out and we've onboarded a few new engineers to empire at this point and haven't run into it.
