### ISSUE TITLE
Environment variable loading broken in 0.12.0 emp client

### ISSUE THREAD

**Issue by WheresWardy** [remind101/empire#1061]
We've recently upgraded an Empire cluster we use to 0.12.0 and I downloaded the 0.12.0 darwin client to use in tandem, but trying to use `env-load` to load environment variables with that client appears to be broken in that it seems to pick a single variable value at random, and then set all of the environment variables to that value (instead of each individual value as in the file).

I've created an example with a new test app with some test values. Using the 0.12.0 version of the client sets everything to the same value, whereas 0.11.0 doesn't.

```bash
$ cat test.env
TEST_VARIABLE_A=myvalue
RANDOM_PORT=5837
DAY_OF_THE_WEEK=thursday

$ /usr/local/bin/emp0.11.0 version
0.11.0

$ /usr/local/bin/emp0.12.0 version
0.12.0

$ /usr/local/bin/emp0.12.0 create mytestapp
Created mytestapp.

$ /usr/local/bin/emp0.12.0 env -a mytestapp

$ /usr/local/bin/emp0.12.0 env-load -a mytestapp test.env
Updated env vars from test.env and restarted mytestapp.

$ /usr/local/bin/emp0.12.0 env -a mytestapp
DAY_OF_THE_WEEK=5837
RANDOM_PORT=5837
TEST_VARIABLE_A=5837

$ /usr/local/bin/emp0.11.0 env-load -a mytestapp test.env
Updated env vars from test.env and restarted mytestapp.

$ /usr/local/bin/emp0.12.0 env -a mytestapp
DAY_OF_THE_WEEK=thursday
RANDOM_PORT=5837
TEST_VARIABLE_A=myvalue
```

**Comment by ejholmes** [comment]
I think this was broken by https://github.com/remind101/empire/pull/990/files via the dreaded "pointer in a for loop":

```go
config := make(map[string]*string)
for key, value := range parsedVars {
        config[key] = &value
}
```

Which should be:

```go
config := make(map[string]*string)
for key, value := range parsedVars {
        value := value
        config[key] = &value
}
```

Lemme see if I can get a test going that repro's this and fix it.

**Comment by ejholmes** [comment]
Fix for this in https://github.com/remind101/empire/pull/1062
