### ISSUE TITLE
Golang SDK

### ISSUE THREAD

**Issue by AlexDee-SP** [remind101/empire#1071]
Hey! First thanks for this awesome platform!

Are there any chances that you'll provide the SDK (at least for Golang) any time soon? These days we can use CLI client, lots of things are written in _cmd/**emp**_ application. But this code is not reusable by any external consumers/applications (since everything is under the _main_ package and is not exportable) so I cannot plug this code into my application. 

The only way of doing it today is to copy-paste code from the _cmd/**emp**_ application into my application. The bad thing about it is that when you update the code on your side, it may brake my application as it might run out of sync with your codebase.

**Comment by ejholmes** [comment]
Hi @AlexDee-SP. cmd/emp just consumes the REST API that Empire exposes, which is a derivative of the [Heroku Platform API spec](https://devcenter.heroku.com/articles/platform-api-reference). You can use the client in [pkg/heroku](https://github.com/remind101/empire/tree/master/pkg/heroku) in a Go application to interact with Empire in a programmatic fashion.

Does that answer your question?

**Comment by AlexDee-SP** [comment]
Hi @ejholmes ! Yes your answer makes absolute sense. Thank you!
