### ISSUE TITLE
unrecognized import path "code.google.com/p/go-uuid/uuid"

### ISSUE THREAD

**Issue by MichaelAquilina** [remind101/empire#1091]
After running `go get` I get the following error:

```
package code.google.com/p/go-uuid/uuid: unrecognized import path "code.google.com/p/go-uuid/uuid" (parse https://code.google.com/p/go-uuid/uuid?go-get=1: no go-import meta tags)
```

It seems like that url is no longer valid and we should be using https://github.com/pborman/uuid

**Comment by ejholmes** [comment]
@MichaelAquilina can you paste the output of `go version`? Note, that you need to be using a version of Go that supports the `vendor/` dir.

**Comment by MichaelAquilina** [comment]
```
$ go version
go version go1.7.5 linux/amd64
```

**Comment by ejholmes** [comment]
gotcha. And are you `go get`'ing a specific path, or `go get`'ing after a clone? Could you paste the exact commands you're running? I'm not able to reproduce locally.

**Comment by MichaelAquilina** [comment]
ah maybe it's just something about go I'm not understanding:
```
$ git clone git@github.com:MichaelAquilina/empire.git   # personal fork
$ cd empire
$ go get
```

**Comment by ejholmes** [comment]
Ah yeah. There's no need to `go get`. [CONTRIBUTING.md](https://github.com/remind101/empire/blob/master/CONTRIBUTING.md) should have everything you need to get started :).

**Comment by MichaelAquilina** [comment]
Thanks for the help @ejholmes :)
