### ISSUE TITLE
Dependencies manager and "code.google.com/p/go-uuid/uuid"

### ISSUE THREAD

**Issue by AlexDee-SP** [remind101/empire#1092]
Hello,

I read questions regarding Google's UUID repository and the Empire usage. I think I have a little bit different case. I use some parts of the Empire codebase in my application (basically, struct definitions), and I need to fix the list of my project dependencies. I've tried to use [Dep](https://github.com/golang/dep) and [Glide](https://github.com/Masterminds/glide) package managers. But they both complain about Goggle's UUID repository:

**Dep output:**
`No versions of github.com/remind101/empire met constraints:
        v0.12.0: unable to deduce repository and source type for "code.google.com/p/go-uuid/uuid": unable to read metadata: go-import metadata not found
`

**Glide output:**
`
[INFO]  --> Fetching code.google.com/p/go-uuid.

[WARN]  Unable to checkout code.google.com/p/go-uuid

[ERROR] Error looking for code.google.com/p/go-uuid/uuid: Cannot detect VCS
`

Empire is the only one package that has "code.google.com/p/go-uuid/uuid" as the dependency. I see, that in the `~/go/src/github.com/remind101/empire/vendor/github.com/remind101/kinesumer/provisioners/redis/provisioner.go` a new repo is used ("github.com/pborman/uuid") but in all other files I see the reference to the old repository.

~ ❯❯❯ go version                                                                                                                                                                                              
go version go1.8 darwin/amd64

What will you suggest in my case?
Many thanks!

**Comment by ejholmes** [comment]
Hi @AlexDee-SP. I think this is something we can fix pretty easily on Empire's side. That package was moved to https://github.com/google/uuid when code.google.com went down, so we just need to update a few references.

You can always work around it by just vendoring the version of that package in `vendor/code.google.com/p/go-uuid/uuid`.

**Comment by ejholmes** [comment]
I just merged in https://github.com/remind101/empire/pull/1093, which should help you here. You can now import `github.com/remind101/empire` with a very minimal set of transitive dependencies (just `github.com/lib/pq`, `github.com/jinzhu/gorm`, and `golang.org/x/net/context`).

There's no longer a dependency on `code.google.com/p/go-uuid/uuid`.
