### ISSUE TITLE
Use Nested Stacks for large applications

### ISSUE THREAD

**Issue by stroebs** [remind101/empire#1106]
Attempting to deploy an application with a large number of environment variables and processes in a Procfile fails due to CloudFormation template size limits. Nested stacks should be used in this case.

Example case: org/mylargeapp
Environment variables: 71
Procfile length: 96 lines/processes

`emp deploy org/mylargeapp -a largeapp`:
latest: Pulling from org/mylargeapp
fdd5d7827f33: Pull complete
a3ed95caeb02: Pull complete
df1d33effda0: Pull complete
890bab076cf5: Pull complete
858cbe0b307b: Pull complete
538a488683df: Pull complete
15179a6bf221: Pull complete
010df3845069: Pull complete
ac1de10b24a0: Pull complete
d90dc458ff8b: Pull complete
6ce0d0b4c190: Pull complete
1c69bbfe6567: Pull complete
4edfcf4b572a: Pull complete
Digest: sha256:539fd0182e6c504c4c17a51fc4c14e192e51b5357463751193aeaa9bd75487b8
Status: Downloaded newer image for org/mylargeapp:latest
Status: Resolved org/mylargeapp:latest to org/mylargeapp@sha256:539fd0182e6c504c4c17a51fc4c14e192e51b5357463751193aeaa9bd75487b8
Status: Extracted Procfile from "/app/Procfile"
Status: Created new release v3 for mylargeapp

> **error:** TemplateValidationError:
>   Template URL: https://empire-paas-templatebucket-{redacted}.s3.amazonaws.com/mylargeapp/{redacted/{redacted}
>   Template Size: **723710 bytes**
>   Error: ValidationError: Template may not exceed **460800 bytes** in size.
> 	status code: 400, request id: {redacted}

References:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html

In addition:

> error: TemplateValidationError:
>   Template URL: https://empire-paas-templatebucket-{redacted}.s3.amazonaws.com/test/{redacted}/{redacted}
>   Template Size: 449350 bytes
>   Error: ValidationError: Template format error: Parameter count 97 is greater than max allowed 60
> 	status code: 400, request id: {redacted}

**Comment by ejholmes** [comment]
Hi @stroebs. There are workarounds for generating a smaller template size by setting `EMPIRE_X_TASK_DEFINITION_TYPE=custom`, which dedupes the environment variables throughout the stack template.

Even if you get past the template size limit, you'll likely run into a CloudFormation limit on the number of resources and/or the number of parameters in a stack.

Splitting up the resources across multiple stacks is something we've thought of, but brings in some added complexity for a fairly uncommon case, so it's unlikely that we'd go down that route.

With that said 90 entires in a Procfile is quite a lot! I would suggest potentially looking into what you can remove from the Procfile and/or split them up across multiple apps.

**Comment by stroebs** [comment]
Thanks for the response @ejholmes. Have indeed run into the aforementioned CF resource limits when reducing env vars to the bare minimum.

We've hit the stage where we realised that splitting our monolithic behemoth into smaller micro services makes sense (and made sense well over a year ago already). I think the temporary solution to start using Empire will be to follow what you suggest and split into several apps.

Thanks for the help!
