### ISSUE TITLE
emp tool silently fails when trying to deploy w/o a commit message

### ISSUE THREAD

**Issue by sumeet** [remind101/empire#1121]
`emp-staging deploy remind101/r101-api:latest -a r101-api` exits silently with code 0, but doesn't actually do anything. turns out it requires a `-m` to actually trigger a deploy

this bug was related to the incident recently where we deployed an ancient version of

the return 0 is misleading, seems like the deploy actually happened when nothing happened. can we fix this in the client?

**Comment by ejholmes** [comment]
Turns out we already have an issue open for this: https://github.com/remind101/empire/issues/1119
