### ISSUE TITLE
need to clean docker images

### ISSUE THREAD

**Issue by phobologic** [remind101/empire#270]
Need to be able to clean up docker images on hosts so that we don't blow out disk space.

**Comment by gileze33** [comment]
Was this fixed recently? I have the cloudformation test stack for our staging environment and just ran up against this issue

**Comment by ejholmes** [comment]
Hey @gileze33. We closed this because it's not really a concern of Empire's. In our environment, we run a [little bash script](https://gist.github.com/ejholmes/f20f4d1efaeb60ec9b52) in a cron job to clean out old images.

**Comment by phobologic** [comment]
We actually do include this script, and run it frequently, in the empire_ami: https://github.com/remind101/empire_ami/blob/master/ansible/roles/docker/files/usr/sbin/docker_maid
