### ISSUE TITLE
cron jobs

### ISSUE THREAD

**Issue by phobologic** [remind101/empire#300]
Need to be able to run scheduled jobs

**Comment by ejholmes** [comment]
Gonna re-open this, because I think we can actually do this pretty easily now with the extended Procfile, CloudFormation backend and the new cron stuff in cloudwatch events.

**Comment by ejholmes** [comment]
Just opened a PR that adds this natively: https://github.com/remind101/empire/pull/919

![](http://gifsec.com/wp-content/uploads/GIF/2014/08/GIF-aww-yea-bite-lip-Christopher-Walken-dat-ass-sexytime-GIF.gif?gs=a)
