### ISSUE TITLE
Document how to enable github authentication

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#345]

**Comment by ferrix** [comment]
Got far enough to need this one. Do it and I'll review instantly. :+1:

**Comment by ferrix** [comment]
So I dug up the variables `grep GITHUB empire/cmd/empire/main.go` and created a new task revision with that. Now I just need the callback url.

**Comment by ferrix** [comment]
My shoelace version of instructions, you are free to use them:

0. Create a new Github Application under your organization with <yourempire>/oauth/authorizations as callback
1. Find the appropriate cluster on AWS ECS Console
2. Select the appropriate service `empir-...`
3. Select the task definition
4. Create new revision
5. Add three environment variables `EMPIRE_GITHUB_CLIENT_ID`, `EMPIRE_GITHUB_CLIENT_ID` and `EMPIRE_GITHUB_ORGANIZATION` with the details you got from Github. Your organization being the one in the URL.
6. Go back to the service and click on Update
7. Select the new task definition (which is TheOldOneXYZ:2 if the previous ended with :1)

**Comment by ferrix** [comment]
And while we're at it, should notice to enable HTTPS before throwing your production credentials over and mention to do that on the respective ELB.

**Comment by public** [comment]
Does enabling GH auth disable the "fake" user?

**Comment by phobologic** [comment]
Definitely need SSL as a part of this.

**Comment by public** [comment]
The answer to my question appears to be yes :)

When you say this should be behind SSL do you image that this would normally be behind an ELB doing the SSL termination?

**Comment by ferrix** [comment]
@phobologic ACK. I'll have a look tomorrow.

**Comment by ferrix** [comment]
@public That's the standard mode of operation. If you want a security in depth approach with this... which would make sense, you would possibly decide not to terminate on ELB. However that is far more complex.

**Comment by phobologic** [comment]
Yeah - in general, the easiest way to do the SSL is to have the ELB terminate it.  The hard part about automating that is that you can't create SSL certificates via Cloudformation, you have to submit them then refer to them in the Cloudformation template.

We're working on the 'production best practices' doc this week, so hopefully we'll have something up for you guys ASAP.

**Comment by crohr** [comment]
Is there any way to restrict github authentication to a specific github team?

**Comment by ejholmes** [comment]
@crohr not right now, but that would be a great addition and should be relatively easy to add by adding a check after [checking the organization](https://github.com/remind101/empire/blob/master/server/authorization/github/github.go#L67-L78). We're also talking about adding an ACL system to restrict access to certain features for certain groups (e.g. some group can't use `emp run` or `emp env`, etc), which may be backed by github teams.

**Comment by crohr** [comment]
@ejholmes sounds great! I'll see if I can make a single team restriction work with my limited Go knowledge ;)

**Comment by ejholmes** [comment]
Going to close this out for now. FYI, team authorization restrictions will be really easy to add after https://github.com/remind101/empire/pull/687.
