### ISSUE TITLE
ECS Gotchas

### ISSUE THREAD

**Issue by phobologic** [remind101/empire#440]
@ejholmes and I were chatting - it seems like it'd be a good idea to have an issue that lists 'gotchas' or outright bugs we've run into with ECS.  This would, hopefully, allow us to share these with Amazon to get work arounds or even help them shape the product somewhat.

* [x] It's possible to create services within a non-existent cluster.
* [ ] Limited visibility into ECS scheduler events.
* [x] No support for logging drivers or labels.
* [x] Not able to determine 'uptime' of tasks

**Comment by pikeas** [comment]
Another gotcha for the list: you can't run more containers of one type than the number of EC2 instances in the cluster. When you combine this with the fact that ECS will add a new container instance before removing old instances, and this means there's a practical limit of N-1 instances of any service, where N is the cluster size.

**Comment by corentone** [comment]
Sorry for the necro, I just wanted to update one point: ECS now has some cloudformation support.

The announce:
https://aws.amazon.com/about-aws/whats-new/2015/06/aws-cloudformation-supports-amazon-ec2-container-service-data-pipeline-lambda-iam-managed-policies/

The docs:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html

**Comment by ejholmes** [comment]
@corentone good catch :). Updated the original issue.

**Comment by ejholmes** [comment]
Most of these are non-issues anymore. Closing.
