### ISSUE TITLE
Post Empire events to an SNS topic.

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#458]
This plays off of @bmarini's idea to add webhooks. SNS might be easier because we can build less. It would be sweet to have events for things like ELB's getting created, processes being scaled, etc.

Some cool consumers we could build:

1. Something that listens for ELB creation events and uses [this](http://dev.librato.com/v1/put/sources/:name) librato api to rename the source to something more meaningful.
2. An app that creates a base librato dashboard when new apps are created.

**Comment by crohr** [comment]
Having some kind of webhook support would also be useful to post deployment/scaling notifications to slack/irc/whatever.

**Comment by mhahn** [comment]
I was just thinking of this today as well. It would also be useful for
auditing who has run a container and when
