### ISSUE TITLE
empire admin tools

### ISSUE THREAD

**Issue by phobologic** [remind101/empire#462]
Using this as a scratch board for ideas for admin tools - if they were integrated as API endpoints with Empire it'd be nice from a future-portability standpoint, but its probably easier to have scripts that talk directly to AWS, etc for the time being:

- Figure out what instance a container is running on
- Map tasks/task-definitions to empire resources

**Comment by ejholmes** [comment]
> Figure out what instance a container is running on

This was done in https://github.com/remind101/empire/pull/983

> Map tasks/task-definitions to empire resources

Much easier now that the ecs service is named after the app in the cf backend.
