### ISSUE TITLE
ssl: one certificate per web app may be an issue

### ISSUE THREAD

**Issue by phobologic** [remind101/empire#471]
Right now, when you add an SSL certificate, it always creates a new one.  Even if, for example, you have a *.<domain> certificate.

An account only has a limit of 20 certificates:

http://docs.aws.amazon.com/IAM/latest/UserGuide/LimitationsOnEntities.html

It might be worth building the certificate name by combining the CN of the cert with the timestamp  and then hashing them.  That way if services share the same cert, we don't have to use up another cert in the IAM system.

**Comment by zachlatta** [comment]
:+1:

**Comment by gileze33** [comment]
It'd be super super cool if we could specify the name or ID of any existing cert in the AWS account

**Comment by mhahn** [comment]
+1, I've started running into that limit now:

```
error: LimitExceeded: Cannot exceed quota for ServerCertificatesPerAccount: 20
	status code: 409, request id: [6eeee662-6c72-11e5-9841-eb45504c0b1d]```

i think this is also a side-effect of some of the commands, `ssl-cert-add` and scaling to adjust cpu/memory units, not working on existing deployments and having to re-deploy the app to get the change.
