### ISSUE TITLE
Document cert / domain behavior

### ISSUE THREAD

**Issue by bmarini** [remind101/empire#498]
- Document how to create a public app (create domain BEFORE deploying)
- Document how to add a cert (add a cert BEFORE deploying)
- Error if trying to add / remove a cert / domain if releases exist.

**Comment by zachlatta** [comment]
See #376 for more details/discussion on domains.

**Comment by phobologic** [comment]
Adding this here, in case other people are curious - if you want to have an externally exposed application, say 'remind101/acme-inc:latest', you should do the following:

```
emp create acme-inc
emp domain-add -a acme-inc acme-inc.example.com
emp deploy remind101/acme-inc:latest
```

**Comment by phobologic** [comment]
Honestly, this gets asked enough that I think we need to ditch the `domain-add` concept, and make it something that isn't a Heroku command.  The whole domain-add thing is just confusing.

**Comment by ejholmes** [comment]
I can pick this up. It'll be easy to implement; mostly just removing stuff.

**Comment by rgabo** [comment]
@ejholmes we have the dreaded `error: currently assigned load balancer is not suitable for the given exposure` also come up if we need to update certificates on the ELBs without downtime. Given that you are removing SSL cert management in the next release (great!), can you let us know when to expect 0.9.3 or 0.10.0?

**Comment by ejholmes** [comment]
@rgabo planning to do a 0.9.3 release early next week!

**Comment by rgabo** [comment]
@ejholmes sounds great, we're running a build from `master` right now so it will be great to pin at `0.9.3` :smile:
