### ISSUE TITLE
Restart is potentially dangerous

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#512]
Currently, restarting relies on stopping ECS tasks. If you blindly restart an entire application, all of the current ECS tasks will be stopped. Ideally, ECS would provide a method to do a rolling restart of some tasks, but that's not a feature at the moment. A potential work around would be to re-submit the service with a new task definition to trigger a rolling restart of all of the tasks.

**Comment by bgentry** [comment]
Was this resolved by #543?

**Comment by ejholmes** [comment]
Yep. Closing.
