### ISSUE TITLE
Access control issues in bootstrap

### ISSUE THREAD

**Issue by ferrix** [remind101/empire#522]
When running `bin/bootstrap`, the process gets stuck and finally is rolled back with the following message:

    Service arn:aws:ecs:eu-west-1:123456789101:service/empir-Servi-J0JVEJLCW8CH did not stabilize.

When digging deeper, apparently the postgres task gets continuously bounced by an authentication problem. Is there something missing from the documentation?

**Comment by ferrix** [comment]
Apparently the `remind101/empire` docker is private.

**Comment by ejholmes** [comment]
@ferrix sorry about that, we had it marked as `unlisted` in the docker registry. Just made a public.

**Comment by ferrix** [comment]
No dice.

    CannotPullContainerError: Authentication is required.

This is on the postgres task.

https://www.dropbox.com/s/k4fodqt0bdj5yck/Screenshot%202015-06-17%2018.13.24.png?dl=0

**Comment by phobologic** [comment]
@ferrix Is the empire task being setup ok?  Can you ssh into the host where the image is failing at, and take a look at:

`docker ps -a`

Find a postgres container, there may be a few of them, then:

`docker logs <container_id>`

We don't maintain the postgres container - we just use the public one, so it's very strange that you'd be having this issue.

**Comment by phobologic** [comment]
Actually @ferrix, another question - are you using `bin/boostrap` or `bin/launch_demo`?

**Comment by ejholmes** [comment]
Possibly related to this? https://status.docker.com/

![](https://s3.amazonaws.com/ejholmes.github.com/r3guS.png)

Pretty sure I've had this happen to me a while back as well.

**Comment by ferrix** [comment]
Still `bin/bootstrap`. I will try when the degradation is over. Thanks for looking into this already.

**Comment by ferrix** [comment]
Both tasks end up failing but not knowing why, I just considered it a cascade effect from not having a database connection.

**Comment by phobologic** [comment]
:+1: I'm going to close this, but if it's still an issue (go figure docker hub would have issues our second day out!) please re-open it.  Thanks @ferrix

**Comment by ferrix** [comment]
Gotcha. I got to the next phase on my nth attempt. n+1 due to compose acting funny locally.

**Comment by phobologic** [comment]
Awesome!

**Comment by ferrix** [comment]
That was a known boot2docker DHCP issue. Now:

    server_1   | 2015/06/15 19:39:48 read /root/.dockercfg: is a directory
    empire_server_1 exited with code 1

This is very interesting.
