### ISSUE TITLE
Combine bootstrap and launch_demo scripts

### ISSUE THREAD

**Issue by bmarini** [remind101/empire#524]
The only difference here is running empire locally vs as part of the cloud formation stack. We can reduce confusion between the two by making them the same script, and improve the documention for which way new users should bootstrap (demo vs development)

**Comment by phobologic** [comment]
There's one other difference, though it probably doesn't matter a ton - the bootstrap script is intended for running empire/postgres locally via docker-compose.  The cloudformation script, however, deploys postgres & empire automatically via ECS.

In the end it shouldn't break anything, but it will probably cause confusion.  With CF Conditionals and a Parameter we should be able to deal with that, though it might be tricky.

**Comment by ejholmes** [comment]
I think we should just have a `bin/bootstrap` script, with a `--dev` (or `--write-env`, etc) flag to write the stack outputs to a .env.

**Comment by ejholmes** [comment]
From the installation guide, it would be nice to also just do what coreos is doing with the Launch Stack buttons here https://coreos.com/docs/running-coreos/cloud-providers/ec2/. This will be easier for some.

**Comment by bmarini** [comment]
:+1: for ./bin/bootstrap with some args

**Comment by phobologic** [comment]
I'll look into this as part of the research I'm doing on the Cloudformation scripts, etc.

**Comment by phobologic** [comment]
Closed by #531
