### ISSUE TITLE
Funny behavior when not logged to docker

### ISSUE THREAD

**Issue by ferrix** [remind101/empire#537]
As the final step to my crusade to install this thing with `bin/bootstrap` I found this thing. I had not logged in to docker locally, so my `~/.dockercfg` was missing. I would get `server1` die on `/root/.dockercfg` being a directory. It actually gets created as a directory on my host home directory. A simple `touch` on the file gives me the same thing and now with something about EOF.

Unless this is something you can fix, document the use of `docker login` before attempting this.

**Comment by ejholmes** [comment]
I think I remember running into this too. `touch`ing `~/.dockercfg` then restarting boot2docker should fix it. I'll see if I can repro again and get the docs cleaned up. Maybe touch `~/.dockercfg` in `./bin/bootstrap` for good measure?

**Comment by ferrix** [comment]
I had to:

    rmdir ~/.dockercfg
    docker login

A simple `touch` would not do. I think `echo '{}' > ~/.dockercfg` could do it because everything needs to be valid JSON these days.

**Comment by ejholmes** [comment]
Documenting the repro for this for anyone that gets into this state:

**To reproduce**

1. Move your ~/.dockercfg somewhere
2. `docker-compose up`
3. You'll see the error message `read /root/.dockercfg: is a directory`
4. `rm -rf ~/.dockercfg` then move your original `.dockercfg` back to `~/.dockerfg`
5. `docker-compose up`
6. You'll see the error message `Cannot start container f9a2cdf5f7fcf6634cc7f8a2d3b46b860df47ad22c95a77b5b982c7e041c49c3: [8] System error: not a directory`

**Fix**

1. Restart boot2docker
2. `docker-compose up` should work now.

I think it would be nice if we just used the `~/.dockercfg` file instead asking for username and password. If they say they want to use a private registry and they don't have a `~/.dockercfg`, do a `docker login`.
