### ISSUE TITLE
GitHub Enterprise Support

### ISSUE THREAD

**Issue by public** [remind101/empire#547]
Currently the GitHub auth support is limited to github.com. We are about to start moving to GHE. Supporting GHE would mean we could reduce the attack surface further and would make administering user access simpler.

**Comment by public** [comment]
Also I am volunteering to implement this as I suspect it will be quite simple and we have access to a GHE instance to test with :)

**Comment by phobologic** [comment]
:+1: That would be awesome.  Being able to run Empire in-house and talking to a private Github Enterprise seems like it'd be useful to quite a few people.  Like you said - we don't have a copy lying around at Remind, so any help you can give would be great.  Let us know if you need a hand.

**Comment by abrkn** [comment]
:+1: You can get a free Github Enterprise tutorial that lasts for some time. I assume they'd extend the trial infinitely given scenario.
