### ISSUE TITLE
Creating additional accounts/changing default username/password

### ISSUE THREAD

**Issue by zachlatta** [remind101/empire#549]
It'd be great if there was documentation on creating additional user accounts and changing the default account from `fake` and no password to something (perhaps) a bit more secure.

**Comment by ejholmes** [comment]
Hey @zachlatta. The default authorizer is just for demo/dev purposes, but it could be made more configurable. In production, you'd probably want to use the [GitHub implementation](https://github.com/remind101/empire/blob/6d3c7b1401d8fca9dbf2ccd488d8383a3105afda/empire/cmd/empire/main.go#L66-L82).

We'll be adding docs about how to configure this. See https://github.com/remind101/empire/issues/545.

**Comment by zachlatta** [comment]
Cool, thanks!
