### ISSUE TITLE
Proposal: Implement `emp run` within Empire

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#550]
Right now, there's a couple of disadvantages with the separate [relay](https://github.com/remind101/empire/tree/master/relay):

1. Since it's separate, it's another dependency you have to run alongside Empire, and you need to configure Empire to know where to find the relay.
2. The relay is fairly complicated to setup, since it requires listening on both HTTP and TCP with TLS.
3. It's difficult to horizontally scale it in it's current implementation (you can only have 1 process running atm).

Now that we've separated out the `emp` CLI, I think it might be worthwhile to break Heroku API compatibility here with something that more closely matches the [attach](https://docs.docker.com/reference/api/docker_remote_api_v1.19/#attach-to-a-container) endpoint of the Docker daemon API. The primary advantages would be:

1. Nothing extra to run. Spin up Empire and `emp run`'s will just work, keeping with our goal of making Empire simple to run.
2. It has no impact on horizontally scaling Empire, since you'll simply attach to the stdout of the container from the HTTP request instead of having to re-connect to a TCP endpoint.

I think the only real disadvantage here is that we'll break `hk run`, but I think it would be worth it.

/cc @phobologic @bmarini

**Comment by phobologic** [comment]
:+1: I'm all for simplifying at the cost of breaking heroku compatibility.

**Comment by zachlatta** [comment]
:+1: agreed with @phobologic

**Comment by bmarini** [comment]
:+1: This will be a much better experience out of the box too.

**Comment by ejholmes** [comment]
Some initial work on this in https://github.com/remind101/empire/pull/553

**Comment by pikeas** [comment]
Might as well keep the current `hk run` around as...`hk-run`?

**Comment by ejholmes** [comment]
Hey @pikeas. Would you want to keep the `hk-run` to use `emp` with Heroku? We're going to be removing the Heroku compatibility for running attached processes within Empire since it can be handled much better by hijacking the connection instead of requiring a separate TCP service.

**Comment by pikeas** [comment]
Not a huge thing for me personally. It doesn't seem like anyone using Empire needs Heroku compatibility, so it's probably fine to diverge as needed.

**Comment by zachlatta** [comment]
Agreed on diverging from Heroku compatibility :thumbsup:.

**Comment by rgabo** [comment]
@ejholmes I know its fresh out of the oven, but we're eager to test the `emp run` functionality and are running `remind101/empire:runner` in one of our environments. I'm getting an `error: Unexpected error: 502 BAD_GATEWAY` on the CLI side while I see meaningful entries in the Empire logs:

```
t=2015-07-01T15:53:24+0000 lvl=info msg=request.start request_id=742d5546-f380-422d-b15d-7c81903294ed method=POST path=/apps/busybox/dynos
t=2015-07-01T15:53:24+0000 lvl=info msg=authenticated request_id=742d5546-f380-422d-b15d-7c81903294ed user=rgabo
t=2015-07-01T15:53:26+0000 lvl=info msg=PullImage request_id=742d5546-f380-422d-b15d-7c81903294ed trace.id=df4e7f37-e5ba-4891-94c1-75081e4d0678 trace.parent= trace.func=github.com/remind101/empire/empire/pkg/dockerutil.(*Client).PullImage trace.file=/go/src/github.com/remind101/empire/empire/pkg/dockerutil/client.go trace.line=79 trace.duration=1.900823769s registry= repository=busybox tag=latest
t=2015-07-01T15:53:26+0000 lvl=info msg=CreateContainer request_id=742d5546-f380-422d-b15d-7c81903294ed trace.id=2b2a9abd-9548-4eb1-a0b0-28313359bef8 trace.parent= trace.func=github.com/remind101/empire/empire/pkg/dockerutil.(*Client).CreateContainer trace.file=/go/src/github.com/remind101/empire/empire/pkg/dockerutil/client.go trace.line=86 trace.duration=114.742031ms image=busybox:latest
t=2015-07-01T15:53:26+0000 lvl=info msg=StartContainer request_id=742d5546-f380-422d-b15d-7c81903294ed trace.id=7cd1c139-a9c8-4b92-ac8f-262b56609089 trace.parent= trace.func=github.com/remind101/empire/empire/pkg/dockerutil.(*Client).StartContainer trace.file=/go/src/github.com/remind101/empire/empire/pkg/dockerutil/client.go trace.line=93 trace.duration=71.073239ms id=20355a5397358f77f907a544453f6bf622cb0dadcc5bf3438842db466e96c5b9
t=2015-07-01T15:53:26+0000 lvl=info msg=AttachToContainer request_id=742d5546-f380-422d-b15d-7c81903294ed trace.id=9fbed2fa-4cf4-4243-89f6-63477d706a4a trace.parent= trace.func=github.com/remind101/empire/empire/pkg/dockerutil.(*Client).AttachToContainer trace.file=/go/src/github.com/remind101/empire/empire/pkg/dockerutil/client.go trace.line=100 trace.duration=1.756511ms container=20355a5397358f77f907a544453f6bf622cb0dadcc5bf3438842db466e96c5b9
t=2015-07-01T15:53:26+0000 lvl=eror msg= request_id=742d5546-f380-422d-b15d-7c81903294ed error="\"write tcp 10.64.3.35:43467: broken pipe\"" line=102 file=/go/src/github.com/remind101/empire/empire/pkg/dockerutil/client.go
t=2015-07-01T15:53:27+0000 lvl=info msg=request.complete request_id=742d5546-f380-422d-b15d-7c81903294ed status=0
```

Any idea why the connection is thrown away before the Empire API would start writing into the TCP connection? Let me know if you have any idea off the top of your head. This is behind an ELB and all trafic is allowed between the ELB and the private subnets where the ECS instances run. Thanks!

**Comment by ejholmes** [comment]
@rgabo you'll need to put the ELB that serves the Empire API into TCP/SSL mode instead of HTTP/HTTPS. In HTTP mode it seems like hijack'ing the connection doesn't play well.

**Comment by rgabo** [comment]
That's right, I remember you discussing it. I've configured the ELB to SSL:443 => TCP:80 but the CLI now seems to hang. Do I need to use a different URL scheme than `https`? I checked `emp/run.go` and it seems to me that TLS will happen for the `https` scheme only. Our ELB is configured to be HTTP/SSL only.

**Comment by rgabo** [comment]
Nevermind, Empire API runs on 8080 while the ELB console defaults back to TCP:80.

**Comment by rgabo** [comment]
The Empire API log shows PullImage, CreateContainer, StartContainer, AttachToContainer but the CLI throws `error: invalid character 'P' looking for beginning of value`. I actually see the container running, but STDOUT/STDERR never arrives.

**Comment by ejholmes** [comment]
@rgabo have you updated to the latest version of the CLI? (`go get -u github.com/remind101/emp`). See https://github.com/remind101/emp. (I'll release a new binary once we've tested this out internally for a while).

**Comment by ejholmes** [comment]
(closing this in the meantime since the pr was merged).

**Comment by rgabo** [comment]
@ejholmes I did, but the official release took precedence in my PATH :smile: Works great now, thanks.

**Comment by ejholmes** [comment]
:metal: let me know if you run into any issues.
