### ISSUE TITLE
Uptime count is wrong when scaling up a new instance?

### ISSUE THREAD

**Issue by public** [remind101/empire#555]
When you increase the number of running instances using the "emp scale" command the up time counter of the new instance seems to borrow from one of the existing ones instead of starting from 0.

e.g.

```
Alexs-MBP-2:python-microservice alexs$ emp scale -a doppelganger web=2
Scaled doppelganger to web=2:1X.
Alexs-MBP-2:python-microservice alexs$ emp ps -a doppelganger 
v26.web.6f06054d-bb78-4231-abd8-3bed4af2f43c  1X  RUNNING  23h  "./bin/web"
Alexs-MBP-2:python-microservice alexs$ emp ps -a doppelganger 
v26.web.6f06054d-bb78-4231-abd8-3bed4af2f43c  1X  RUNNING  23h  "./bin/web"
v26.web.a3eaa100-7d92-4909-860f-73dc5b7b59a2  1X  RUNNING  23h  "./bin/web"
```

**Comment by ejholmes** [comment]
The uptime count is currently the time from when the task definition was submitted. This requires changes from ECS to support timestamps for state changes. Doesn't seem to be a lot that we can do about this right now unfortunately, unless I'm missing something in the ECS API.

/cc @euank

**Comment by euank** [comment]
The ECS API, indeed, doesn't offer that information. I'll add that as a feature request.

**Comment by phobologic** [comment]
Thanks @euank
