### ISSUE TITLE
Slow startup?

### ISSUE THREAD

**Issue by pikeas** [remind101/empire#558]
I've tried to spin up empire twice. Each time, CloudFormation seems to have gotten "stuck" on one of the creation steps. I'm hoping that if I let it sit for an hour or so, things will eventually sort themselves out.

If it's normal behavior for startup to take, say, longer than 5-10 minutes, it would be great if the docs mentioned an expected wait time from starting `./bin/bootstrap` through completion.

**Comment by phobologic** [comment]
Hey @pikeas - that's really strange.  It can take a few moments for Cloudformation to finish, though it can vary wildly depending on a lot of factors.  That said, have you taken a look at the Cloudformation console to see what step is taking so long?  That would help with troubleshooting the issue.

**Comment by pikeas** [comment]
I've tried a few more times and have hit the same failure. Repro is:

1) Using empire cloned from master.
2) `./bin/bootstrap`
3) Wait forever (10-30 minutes).
4) End state for Cloudformation stack is ROLLBACK_FAILED.

Output on Cloudformation events will look like: `Service arn:aws:ecs:us-east-1:594131916146:service/empir-Servi-1IHV3M0W7DO4Q did not stabilize.`

I've gotten the same result on five attempted bootstraps. Let me know what additional info I can provide to help debug.

**Comment by phobologic** [comment]
Is that the only event that failed?  Were EC2 instances ever launched?  Can you create ECS Services/Task Definitions/Tasks manually outside of the bootstrap script?

This is very strange - I haven't seen this issue yet.  It's a little late here, but I'll verify that I can launch via the script in the morning.

**Comment by pikeas** [comment]
ECS services/task definitions/tasks: yes, I've had a running task in the default ECS cluster for about a week, running steadily on one instance.

It doesn't look like any EC2 instances were ever created, which explains why the service was unable to launch. However, I don't see any error states on Cloudformation regarding instances. Any thoughts on which resources I should inspect manually while the stack is spinning up?

**Comment by pikeas** [comment]
So, this was a PEBCAK () issue. It looks like I never accepted the T&C for the AMI. The good news is, now you know the failure mode for this oversight. :-) Could be worth a mention in a FAQ section.

**Comment by phobologic** [comment]
Ahhh - ok, yeah, that makes sense.  Glad it got worked out!

**Comment by bloodfire91** [comment]
@pikeas I'm getting the same issue as you had; could you explain what the T&C is?

**Comment by pikeas** [comment]
T&C = Terms and Condition. You'll get stuck if you don't accept the user agreement for the AMI.
