### ISSUE TITLE
Document unchangeable infrastructure

### ISSUE THREAD

**Issue by pikeas** [remind101/empire#560]
Which parts of the Empire stack cannot be modified, because empire/emp depend on their existence/exact configuration?

For example, it looks like I can tweak subnets, change CPU/memory sizing on ECS tasks, and otherwise tweak the stack. How far can I push it - which parts are hands-off (hard-coded names, ports, IPs, etc) due to expectations made by empire's or emp's codebase?

**Comment by ejholmes** [comment]
Good idea. Gonna use this issue to keep track of those things.

The first thing that comes to mind is the port allocations, which uses a [static list of 1000 ports](https://github.com/remind101/empire/blob/master/empire/migrations/0004_add_ports.up.sql#L8) to allocate from. This could be a problem for some.

**Comment by ejholmes** [comment]
A lot of ELB settings are also currently unchangeable via Empire, like [connection draining timeout](https://github.com/remind101/empire/blob/1b09decdf188504f825c1a36de183b6b4728327e/pkg/lb/elb.go#L17), listening mode, health checks, etc. These can be changed within the AWS console after they've been created though.
