### ISSUE TITLE
Private vs public subnets?

### ISSUE THREAD

**Issue by pikeas** [remind101/empire#565]
The bootstrap script has the following:

```
echo "EMPIRE_EC2_SUBNETS_PRIVATE=$(output Subnets)" >> .env
echo "EMPIRE_EC2_SUBNETS_PUBLIC=$(output Subnets)" >> .env
```

And in cloudformation.json:

```
{
  "Name": "EMPIRE_EC2_SUBNETS_PRIVATE",
  "Value": { "Fn::Join": [ ",", [{ "Ref": "PubSubnetAz1" }, { "Ref": "PubSubnetAz2" }] ] }
},
{
  "Name": "EMPIRE_EC2_SUBNETS_PUBLIC",
  "Value": { "Fn::Join": [ ",", [{ "Ref": "PubSubnetAz1" }, { "Ref": "PubSubnetAz2" }] ] }
}
```

So, er, what's the story with the AZ subnets? They're not both public *and* private, so one of these is incorrect or misleading.

**Comment by rgabo** [comment]
@pikeas as far as we've seen, internet-facing external load balancers are placed on the public subnets and the internal load balancers are placed on the private subnets. Think of ELB as nothing else than a bunch of EC2 instances that AWS scales up and down for you. That's why ELBs have subnet assignments and security groups.

In Empire specifically, if the application has a domain added using `emp domain-add` **before** it is **deploy**ed, it will get an external, internet-facing ELB, otherwise it will be internal. So `create` first, use `domain-add` and `ssl-cert-add` to configure the application and only deploy afterwards to have everything set up properly. Deploying first will **not work**.

**Comment by phobologic** [comment]
Yeah, it's mostly an ELB thing at this point.

The Demo doesn't give a good indication of it, but I believe it is in the production guideline docs. We tend to keep the minions (and even the controllers) in the private subnets.  These subnets cannot be accessed directly from the internet.  Instead they have to be accessed via ELBs (or hosts, we have a pair of bastion hosts in the public subnet as well in our environment for the rare case we need to ssh in) in the public subnet.

One particularly easier way we've found of exposing our apps is to use a 'router' app that has been setup as exposed externally via the create/domain-add/ssl-cert-add that is a simple nginx app with routing rules in the config for internal services (using empires internal service discovery).

**Comment by pikeas** [comment]
I'm a bit unclear on what your 'router' app is doing. Are you saying you have:

1) minions in private subnet
2) empire-deployed app tasks not exposed publicly (so internal LB only, no external LB)
3) empire-deployed nginx router app with external LB. Basically just a simple set of server blocks mapping to the above apps.

Is your router app shareable? Would love to verify we're on the same page. Beyond that, it's worth getting the demo stack (which is how 99% of people will spin up the project) closer to a production setup that matches the way you guys actually use empire in the real world - separate subnets, this router if applicable, etc.

**Comment by ejholmes** [comment]
@pikeas yup, that's the general idea. I have an example repo at [ejholmes/empire-demo](https://github.com/ejholmes/empire-demo) (still a WIP) that shows a stripped down version of this setup. Our goal is to eventually share our production setup, but we have no immediate plans to do that. Our goal with the demo stack is to keep it as simple as possible, and make it easy to debug.

**Comment by pikeas** [comment]
@ejholmes Thanks for the link.

Regarding the production setup, this is a great project and I'm sure the community would be happy to help with that portion, myself included. Perhaps you could start an issue with a checklist of what needs to be implemented to bridge the gap between demo mode and prod?

**Comment by pikeas** [comment]
Also, the public router app seems like a great place to use Kong: getkong.org

**Comment by ejholmes** [comment]
@pikeas yup! Kong looks pretty cool. Our main beef with it is that it requires cassandra as a storage engine. For what we do with our router currently, static nginx configuration works well and doesn't introduce any dependencies that can fail.

**Comment by phobologic** [comment]
Yeah, also keep in mind that doesn't mean you can't use Kong - just that we don't use it here @Remind.  I blame our company value of 'Simple', which is something we're shooting for in Empire. :)
