### ISSUE TITLE
Add ECS implementation of `Run` method.

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#570]
When running detached processes, we should run them with the [RunTask](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html) API call. We'd basically want to:

1. Create a Task Definition for the run process.
2. RunTask using the created TD.

https://github.com/remind101/empire/blob/f70a5e2f1b10ec8ee7710847c22befa7efdf5bd4/empire/pkg/service/ecs.go#L291-L302

**Comment by ejholmes** [comment]
One thing to consider here is that in the above scenario, the running task would need by visible with `emp ps` since ps only looks at ECS services. If the `Instances` method was changed to look through Task Definitions instead, that might work better. Ideally, ECS would just support tags on tasks so that we could query for tasks with `app=<app>` tag.

**Comment by crohr** [comment]
Would be really nice to have this feature. Right now it's a bit of a pain to not being able to automatically run migration tasks from our CI for our staging platform. Is the `expect` workaround described in https://github.com/remind101/emp/issues/28 the only way to do it for now?

**Comment by ejholmes** [comment]
Hey @crohr.

Unfortunately that workaround is probably the best way to run one off tasks in an automated way right now. We definitely want to support detached runs, but we're a little tight on resources dedicated to Empire so no eta on this.
