### ISSUE TITLE
CloudFormation backend?

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#578]
Now that CloudFormation supports ECS resources, we could use CloudFormation directly as a backend, rather than using the ECS/ELB/Route53 API's directly. This would remove a lot of nitty gritty manual work like changing listeners and healthchecks.

**Comment by ejholmes** [comment]
The more I think about this the better it sounds. I think there's a couple of key advantages here:

1. The biggest advantage is that we can templatize deployments. We can provide a base text/template for a cloudformation stack that takes in a `service.App` as data and creates the ECS services, linked ELB's, etc but this will allow people to add additional resources to each stack that gets created, even custom resources for provisioning third party services (e.g. kinesis streams, honeybadger projects, papertrail/sumo drains, etc) making it far more extensible than the current backend.
2. We'd ultimately end up removing a lot of code since we'd only need to generate a cloudformation template and talk to one API.
3. Adding support for automatically adding attached resources (RDS), would be really easy.

I think the only drawback is the migration from the old backend to the new backend. We could add a `Migration` implementation of `service.Manager` that uses the new cloudformation backend, and ensures the old ECS/ELB's are destroyed.

**Comment by public** [comment]
In practice how does updating a task definition work in CloudFormation? It the docs it says changing the docker image you have deployed requires replacing the entire Task but does that manifest as a new version of a task or as destroying the task entirely and recreating it?

**Comment by ejholmes** [comment]
CloudFormation will create a new task definition with a random name (it doesn't create a new revision of the existing task definition), which would be fine for Empire since we never actually use the revision directly.

**Comment by ejholmes** [comment]
Also, if we do implement a cloudformation backend, we'd continue to maintain the existing backend and eventually deprecate it depending on how the new backend works.

**Comment by public** [comment]
I kind of like this idea since being able to create new RDS instances and stuff when you deploy your app would be pretty handy sometimes. It does feel a little bit like feature creep at this stage though. I guess this is mostly because we'd rather use Terraform for managing these kind of things right now but that might not be a great reason to dislike this idea.

I have some vague idea of the concept of a "provisioning container" which Empire could execute on each deploy in some context with just enough IAM permissions to create or update the rest of the service. This would decouple Empire (the current service) from any particular provisioning scheme and would make it mostly a system that managed access controls. This has the advantage of meaning Empire can run with fewer permissions and would also potentially make the actual provisioning system pluggable. This could also be called an even more extreme example of feature creep I suppose :)

**Comment by ejholmes** [comment]
That's an interesting idea. If I'm understanding correctly, basically an implementation of the [service.Manager](https://github.com/remind101/empire/blob/master/pkg/service/service.go#L114-L130) interface that might just call out to a Docker container, and when you configure Empire, you could pass it a Docker image to run. Kinda like a loose plugin system for the backends.

That actually sounds like it could be really awesome. It would make extending Empire's provisioning to suit your own needs a lot easier, without needing to merge anything in here, since the actual backend implementations could be externalized and maintained separately.

**Comment by ejholmes** [comment]
Just spewing a few more thoughts:

Maybe the best thing to do is just to define an HTTP version of the service.Manager interface (e.g. `POST /apps`, `DELETE /apps/:id`, `GET /apps/:id/instances`, `PATCH /apps/:id/processes/:type`, `DELET /apps/:id/instances/:task`). The default backend can just assume that the backend API is available at `http://backend`. For most cases, I think just starting Empire with docker and linking to the backend container would suffice (e.g. `docker run -link backend remind101/empire`).

This would provide a lot of flexibility; if you're not using docker to run Empire, that's fine and you can just point Empire to the location of the backend.

I think before we settled on a spec for the API, I'd want to do a little investigation on whether the interface will work well enough for other potential backends (e.g. GCE, Kubernetes, Swarm).

**Comment by ejholmes** [comment]
Another potential benefit to externalizing this interface: Building a cron scheduler would be pretty easy. A separate cron service could easily hit the `/apps/:id/run` endpoint to run the task.
