### ISSUE TITLE
Running a container on every instance

### ISSUE THREAD

**Issue by gileze33** [remind101/empire#596]
Hey Guys,

I've been investigating running empire for our staging environment and so far everything is going great.

My next task is working out how to get decent monitoring and logging from the host & containers - seems like there's quite a few options we can use where you run an image on each instance and it can collect the logs. Would this be possible with empire? It seems like we don't get a choice of where containers are run?

Or is this a general issue with ECS and maybe it would be better to use a custom AMI?

Thanks!

**Comment by ejholmes** [comment]
Hey @gileze33, there's ways to do it with ECS, but we use custom AMI's for our base hosts that includes our logging and metrics infrastructure. It's fairly specific to how we do logging and metrics at Remind but basically is just ubuntu, docker, ecs agent and sumologic.

Hope that helps!

**Comment by phobologic** [comment]
Hey @gileze33, just to follow up on what @ejholmes said - you should check out https://github.com/remind101/empire_ami - the way we launch ecs_agent & empire (you can see it in their own roles, we basically just deploy upstart jobs on the appropriate hosts that pull down & launch the containers we need, totally outside of ECS).
