### ISSUE TITLE
Can't specify the app when deploying via emp

### ISSUE THREAD

**Issue by mhahn** [remind101/empire#615]
I'm curious how you all handle DB migrations within empire. The way I was thinking about doing it was having two apps within empire `api` and `api-migrations`.

`api` would have the external domain attached to it and several web processes running. `api-migrations` would have no external domain and no web processes.

for a release that required migrations, i would like to do something like the following:
```
$ emp deploy -a api-migrations mhahn/api
$ emp run -a api-migrations python manage.py migrate --no-input
# now that migrations are complete, deploying is safe
$ emp deploy -a api mhahn/api
```

DeploymentsCreateOpts supports specifying the app, but this isn't exposed via emp cli. Is this intentional? Is there a more preferred way to do what I'm looking for?

**Comment by ejholmes** [comment]
@mhahn we basically treat it like we did when we were on Heroku. Since ECS is going to do a zero downtime deploy (spin up new processes, health check them, tear down the old ones after connections have drained), any release with migrations needs to be backwards compatible with the last release. So, when we're about to merge a PR, we separate out the migrations first and deploy those, run them, then deploy the code that uses them.

**Comment by ejholmes** [comment]
Regarding specifying the app when deploying, yeah, we want to support that. Just needs a new API endpoint (probably `POST /apps/{app}/deploys`) and CLI support.

**Comment by mhahn** [comment]
I think I'm missing something when trying to test these changes.

I've followed the steps listed here: https://github.com/remind101/empire#development.

After making the changes I do the following:

```
# within $GOPATH/src/github.com/remind101/emp
$ godep go build # to build the new cli with my changes

# within $GOPATH/src/github.com/remind101/empire
$ make build
$ docker-compose up
```

i can see that the cli changes are present and the new URL is being hit in the output from docker-compose, but its returning a 404. I tried testing adding some basic URLs within https://github.com/remind101/empire/blob/master/server/heroku/heroku.go#L19 but all of them return 404s. Did I miss some build step or is there somewhere else the URLs should be added?

**Comment by mhahn** [comment]
and by test I mean, test against a local empire dev server. i wrote unit tests and those are passing.

**Comment by ejholmes** [comment]
If you're making changes to empire, you'll need to rebuild the image that docker-compose uses:

```console
$ docker-compose build
$ docker-compose up
```

**Comment by mhahn** [comment]
ah, cool.

it would be great to have better docs around hacking on empire, i think you guys already have that structure laid out here: https://github.com/remind101/empire/issues/545. i can help add setup/testing docs from the perspective of someone who doesn't use go ever :).

**Comment by ejholmes** [comment]
Definitely. A lot of that knowledge just lives in our heads right now. We've got plans to flesh out the documentation soon, and improve the dev setup too. Definitely would be helpful to get some input from your perspective.
