### ISSUE TITLE
emp fails with self-signed certificates

### ISSUE THREAD

**Issue by brianz** [remind101/empire#617]
`emp` fails when using a self-signed ssl certificate.  To generate and upload a new ssl certificate:

http://git.io/vYPHI

When that certificate is used for Empire, commands result in the following:

```
$ emp apps
error: Get https://empire.brianz.bz/apps: x509: certificate signed by unknown authority
```

This certificate was added to Keychain on my Mac, and Safari seems happy with it:

<img width="709" alt="screenshot 2015-07-27 16 52 47" src="https://cloud.githubusercontent.com/assets/190550/8919843/10ce819a-3480-11e5-9cb1-0af05bd1dbfe.png">

<img width="568" alt="screenshot 2015-07-27 16 41 50" src="https://cloud.githubusercontent.com/assets/190550/8919845/159ad264-3480-11e5-8031-bb74a55a75b1.png">

@phobologic suggests this may be an issue with the way Go handles certs:

https://groups.google.com/forum/#!topic/golang-nuts/v5ShM8R7Tdc

**Comment by phobologic** [comment]
Please open in https://github.com/remind101/emp - thanks :)
