### ISSUE TITLE
Problem with deploying image from unofficial registry

### ISSUE THREAD

**Issue by bronislav** [remind101/empire#624]
In case deploying image from unofficial registry empire pass `registry` param to the docker remote API. This parameter actually wasn't implemented at all and only present in the documentation. I have made a pull request with simple implementation (docker/docker#15093), but after discussion they most likely will fix documentation instead of merging PR.

So, it's quite necessary that someone change parameters that passes to the docker to make empire deployments work properly.

**Comment by stevvooe** [comment]
Does adding `FROM myregistry.com/myapp` not work for this case?

**Comment by bronislav** [comment]
@stevvooe the problem not in Dockerfile.

**Comment by stevvooe** [comment]
@bronislav Ok, so does `fromImage=myregistry.com/myapp` not work correctly?

**Comment by bronislav** [comment]
Your approach works. But empire use additional query parameter `registry` and do not include this information in the `fromImage` parameter.

**Comment by ejholmes** [comment]
This is officially supported after https://github.com/remind101/empire/pull/692 is merged.

**Comment by xiongchiamiov** [comment]
Does [the documentation](https://empire.readthedocs.org/en/latest/known_limitations/#unable-to-use-non-standard-registry) need to be updated, then?
