### ISSUE TITLE
Silent failure when IAM permissions missing

### ISSUE THREAD

**Issue by pikeas** [remind101/empire#626]
Since the current CloudFormation config has overly broad permissions (#579), I configured my Empire controller to use an IAM user role with no access rights as a test. My plan was to run `emp` commands that I expected to fail with PermissionDenied errors, open up the role, and iterate until everything works.

However, Empire is failing silently:

```
$ emp deploy remind101/acme-inc:latest
...
Status: Image is up to date for remind101/acme-inc:latest

$ emp ps -a acme-inc
<blank output>

$ emp scale -a acme-inc web=2
error: ServiceNotFoundException: Service not found.
	status code: 400, request id: []
```

No service or load balancer is created on AWS, but as far as Empire is concerned, the request completed successfully.

Some endpoints did error successfully. I needed to add `ecs:ListServices` to get this far. Why is service creation failing silently?

**Comment by phobologic** [comment]
Are you checking the logs of the empire daemon?  If it isn't loud enough, you should also try running the Empire daemon with EMPIRE_AWS_DEBUG set.

If you'd like to see somewhat tighter policies, you could also checkout the stacker blueprint policies:

https://github.com/remind101/stacker/blob/master/stacker/blueprints/empire/policies.py

**Comment by pikeas** [comment]
Yep, just discovered and enabled `EMPIRE_AWS_DEBUG`. I now have some evidence of the failures:

```
---[ RESPONSE ]--------------------------------------
HTTP/1.1 403 Forbidden
Content-Length: 386
Content-Type: text/xml
Date: Fri, 31 Jul 2015 02:41:25 GMT
X-Amzn-Requestid: a36131b3-372d-11e5-98b0-5363c1742e73
```

This is better, but the failed request IDs aren't displayed on CloudTrail - I'm looking into that to see if I need to add some additional config on the AWS side.

However, the fact that Empire is showing success when AWS is clearly returning 40x failures for the API calls seems like a Big Deal. Can you confirm that you're seeing the same behavior on your end by intentionally restricting Empire on a test cluster?

**Comment by phobologic** [comment]
Hmm - I may not be able to get to it tonight, but how are you defining 'showing success'?  The deploy command successfully pulling down the image you mean and not throwing an error?

**Comment by pikeas** [comment]
@phobologic As far as I know, the deploy command should a) download the image, b) create a task definition, c) create a service from that definition, and d) create a load balancer for the service.

When using an underprivileged user, only a) succeeds. The rest of the steps are failing silently - you only see the failed API requests with EMPIRE_AWS_DEBUG enabled.

If any of Empire's AWS API requests fail, the failure should be shown to the user instead of swallowed.

**Comment by pikeas** [comment]
I worked my way forward by inspecting the controller's logs with EMPIRE_AWS_DEBUG enabled. However, after adding a good chunk of permissions, I'm now blocked at:

```
t=2015-08-02T20:39:20+0000 lvl=info msg=CreateService request_id=... trace.id=... trace.parent= trace.func=github.com/remind101/empire/pkg/ecsutil.(*ecsClient).CreateService trace.file=/go/src/github.com/remind101/empire/pkg/ecsutil/ecs.go trace.line=50 trace.duration=82.980599ms service-name=... desired-count=1 task-definition=...

t=2015-08-02T20:39:20+0000 lvl=eror msg= request_id=... error="\"InvalidParameterException: Unable to assume role and validate the listeners configured on your load balancer.  Please verify the role being passed has the proper permissions.\n\tstatus code: 400, request id: []\"" line=52 file=/go/src/github.com/remind101/empire/pkg/ecsutil/ecs.go
```

As a sanity check, I opened my permissions back up to:

```
ec2:*
ecs:*
elasticloadbalancing:*
iam:*
route53*
```

Even wide open like this, the controller throws the error above. Unfortunately, it doesn't show which role it's trying to assume, so I'm not sure what's broken. My instance and service roles are configured per the ECS docs, but it's not clear why Empire would need to access either of these roles directly.

**Comment by phobologic** [comment]
I'm actually working on (today) having emp get better output when you fail at an `emp deploy` today due to permissions.

You are running this via `DEMOMODE=0 bin/bootstrap` right?  If so, in your .env you'll have a line like this: `EMPIRE_ECS_SERVICE_ROLE=`

Does your controller have the ability to assume the role that is listed there?  Does that role exist?  Does it have the policy defined here?

http://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_IAM_role.html

Here's another example of how that is defined: https://github.com/remind101/stacker/blob/4530c00b472d5deab4ca42e1dd8da89dfdb7d2a5/stacker/blueprints/empire/policies.py#L27

**Comment by pikeas** [comment]
@phobologic I'll try your `emp deploy` changes as soon as they're pushed!

I'm running Empire via a custom setup on Terraform, but it's heavily influenced by your CF template. My controller is still running as an ECS service behind an ELB. The controller's IAM user policy has `iam:*` (temporarily), so it *should* be able to assume the service role, which has the policy you linked to.

**Comment by phobologic** [comment]
Does your ECS service have the following environment variable set?

```
                "Name": "EMPIRE_ECS_SERVICE_ROLE",
                "Value": { "Ref": "ServiceRole" }
```

Also - make sure that it is pointing at a Role that has the right assumerole policy and the right policy document with all the permissions it needs:

```
    "ServiceRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "Path": "/",
        "AssumeRolePolicyDocument": {
          "Version": "2008-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [ "ecs.amazonaws.com" ]
              },
              "Action": [ "sts:AssumeRole" ]
            }
          ]
        }
      }
    },

    "ServiceRolePolicies": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "ecsServiceRole",
        "Roles": [ { "Ref": "ServiceRole" } ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "ec2:Describe*",
                "elasticloadbalancing:*",
                "ecs:*",
                "iam:ListInstanceProfiles",
                "iam:ListRoles",
                "iam:PassRole",
                "route53:*"
              ],
              "Resource": [
                "*"
              ]
            }
          ]
        }
      }
    },
```

Finally, you should make sure that the instance itself has an InstanceProfile with a Role & Policy that allows it to do the following:

```
    "InstanceRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "Path": "/",
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [ "ec2.amazonaws.com" ]
              },
              "Action": [ "sts:AssumeRole" ]
            }
          ]
        }
      }
    },

    "InstancePolicies": {
      "Type": "AWS::IAM::Policy",
      "Properties": {
        "PolicyName": "ecs",
        "Roles": [ { "Ref": "InstanceRole" } ],
        "Users": [ { "Ref": "User" } ],
        "PolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "ec2:Describe*",
                "elasticloadbalancing:*",
                "ecs:*",
                "iam:ListInstanceProfiles",
                "iam:ListRoles",
                "iam:PassRole",
                "iam:UploadServerCertificate",
                "iam:DeleteServerCertificate",
                "route53:*"
              ],
              "Resource": [
                "*"
              ]
            }
          ]
        }
      }
```

My guess is that there is an issue with your InstanceRole/Profile/Policy - or that you're pointing at the wrong role when it tries to assume role.

**Comment by pikeas** [comment]
Arg, looks like `EMPIRE_ECS_SERVICE_ROLE` can only be the role *name* - both ARN and unique ID will fail with an "Unable to assume role" exception.

Worth documenting somewhere if possible.
