### ISSUE TITLE
The "Launch Stack" link references a template without read permissions on S3

### ISSUE THREAD

**Issue by sordina** [remind101/empire#631]
The ["Launch Stack"](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#cstack=sn%7Eempire%7Cturl%7Ehttps://s3.amazonaws.com/empirepaas/cloudformation.json) link from /README.md references [an ECS template](https://s3.amazonaws.com/empirepaas/cloudformation.json) that doesn't appear to have read permissions.

The response that comes back from the S3 URL is

    lyndon@endpin ~ curl https://s3.amazonaws.com/empirepaas/cloudformation.json | xmllint --format -
    <?xml version="1.0" encoding="UTF-8"?>
    <Error>
      <Code>AccessDenied</Code>
      <Message>Access Denied</Message>
      <RequestId>9CD58D72F7FD1552</RequestId>
      <HostId>9gjFk7owam5VR+I/1wdgBLosv9UD44CGxJKog+X6lBgUq8xdC8kzh7mG93kZNRvq</HostId>
    </Error>

This appears to be a permissions issue with the S3 bucket, but it may be that this behaviour is intentional and the user requires extra permissions before this step is performed. If that is the case then the issue is that this is not documented.

I'm experimenting with Empire for the first time this week so please go easy on me if this isn't really an issue :)

**Comment by phobologic** [comment]
Hey @sordina - sorry for the confusion.  Not sure what happened to the bucket there, but I've gone ahead and opened up the bucket so that people can see the template.  Did it give you trouble, before, when you tried the 'Launch Stack' link, or was it just a problem when you went to look at the Cloudformation template via curl?

Thanks for letting us know about this!

**Comment by crohr** [comment]
@phobologic I can confirm the link was broken for me as well when trying to launch the stack or hitting it via curl. It works now.

**Comment by phobologic** [comment]
Cool - yeah, turns out it's an issue w/ the way we upload the file.  It gets overwritten.  @ejholmes is taking a look now.

**Comment by ejholmes** [comment]
The circle ci task that auto uploads the cloudformation stack to s3 wasn't marking it with `public-read`. Sorry about that! Fix in https://github.com/remind101/empire/pull/633

**Comment by sordina** [comment]
Thanks guys!
