### ISSUE TITLE
LaunchStack rollback with an error

### ISSUE THREAD

**Issue by rodlogic** [remind101/empire#636]
I am trying to launch empire's stack using the following I found this repo:
https://console.aws.amazon.com/cloudformation/home?region=us-east-1#cstack=sn%7Eempire%7Cturl%7Ehttps://s3.amazonaws.com/empirepaas/cloudformation.json

However, I got the following error:
```
12:35:38 UTC-0400 	DELETE_IN_PROGRESS 	AWS::Route53::HostedZone 	InternalDomain 	
	12:35:08 UTC-0400 	ROLLBACK_IN_PROGRESS 	AWS::CloudFormation::Stack 	empire 	The following resource(s) failed to create: [InternalDomain, PubSubnetAz1, PublicRouteViaIgw, InstanceProfile, PubSubnetAz2]. . Rollback requested by user.
	12:35:05 UTC-0400 	CREATE_FAILED 	AWS::EC2::Subnet 	PubSubnetAz2 	Resource creation cancelled
	12:35:05 UTC-0400 	CREATE_FAILED 	AWS::IAM::InstanceProfile 	InstanceProfile 	Resource creation cancelled
	12:35:05 UTC-0400 	CREATE_FAILED 	AWS::Route53::HostedZone 	InternalDomain 	Resource creation cancelled
	12:35:05 UTC-0400 	CREATE_FAILED 	AWS::EC2::Route 	PublicRouteViaIgw 	Resource creation cancelled
	12:35:04 UTC-0400 	CREATE_FAILED 	AWS::EC2::Subnet 	PubSubnetAz1 	Value (us-east-1a) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1c, us-east-1e, us-east-1b, us-east-1d.
	12:35:03 UTC-0400 	CREATE_IN_PROGRESS 	AWS::EC2::Subnet 	PubSubnetAz2 	Resource creation Initiated
```

**Comment by phobologic** [comment]
Hey @rodlogic - how did you launch the stack?  Did you do it from the Cloudformation web UI? via bin/bootstrap?

If you did it via the Cloudformation web ui, or even via the aws cli or another library, what's happening is that you are trying to use an Availability Zone that does not allow VPC subnets - it's kind of annoying, but not all AWS AZs can have VPC subnets.  You need to pick subnets from the list that it gave you (in the cloudformation error):

```
    12:35:04 UTC-0400   CREATE_FAILED   AWS::EC2::Subnet    PubSubnetAz1    Value (us-east-1a) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1c, us-east-1e, us-east-1b, us-east-1d.
```

Note: bin/bootstrap should have figured this out for you, provided you didn't override the availability zones that it automatically figures out for you.

**Comment by rodlogic** [comment]
I copied and pasted the cloudformation template link into a FF session I had open with AWS. So yes, cloudformation web ui.

I didn't use the ./bin/bootstrap since it seemed to use a different template that wasn't as secure (?).

If this list of zones is fixed for each region, we could add a mapping to select the subset based on the region the template is launched in.

**Comment by phobologic** [comment]
Unfortunately it's not a fixed list - your us-east-1a is different than my us-east-1a behind the scenes, and not everyone has the same list of AZs.  It's a pain to deal with - we figure it out via API calls in bin/bootstrap, and I have done the same in a lot of places with various API libraries.  I wish they'd give us a Cloudformation variable that gave a list of valid AZs for VPC in an account, but that doesn't exist yet.

Going to go ahead and close this.

**Comment by rodlogic** [comment]
@phobologic Does bootstrap creates the same infrastructure? The comment before running the command is clear in saying that it is a simplified one.

**Comment by phobologic** [comment]
The cloudformation that you're getting from the s3 bucket is the same cloudformation that is stored in https://github.com/remind101/empire/blob/master/docs/cloudformation.json - it's just put into S3 so that it can be referenced directly by cloudformation.

So long answer short - yes, they're the same, and shouldn't be considered 'production ready' in any sense of the word.

If you're looking for a more production ready Empire, you should check out: https://github.com/remind101/stacker/tree/master/conf/empire
