### ISSUE TITLE
Unsure of how to integrate with GH deploys API

### ISSUE THREAD

**Issue by gileze33** [remind101/empire#639]
Hey Guys,

Got the cluster setup nicely, just trying to automate our CI/CD via CircleCI. I have images being built with the SHA as the tag on dockerhub, but viewing the link below it looks like the next step is to setup a 'deploy' webhook in github to ask the Empire process to begin a deployment. Does that sound right? If not, what's the easiest way to trigger an automated deployment from Circle once the docker images are built?

http://empire.readthedocs.org/en/latest/configuration/

Thanks again for such an awesome platform!

**Comment by ejholmes** [comment]
Hey @gileze33. You're on the right track. Once you've configured the environment variables on Empire, you'll just need to add a webhook to the repo you want to be able to deploy. Once you've added a webhook to send `deployment` events to your Empire instance, you can setup your circle CI task to create the deployment request on a successful build (you could use the [deploy](https://github.com/remind101/deploy) command to do this or just CURL the [github deployments api](https://developer.github.com/v3/repos/deployments/)).

If you don't want to go through the trouble of setting up GitHub deployments, you could also just have a deployment section in CircleCI that uses `emp` to deploy your image:

```yml
deployment:
  empire:
    branch: master
    commands:
      - EMPIRE_API_URL=<url> emp deploy gileze33/<repo>:$CIRCLE_SHA1
```
