### ISSUE TITLE
App ELBs should have cross-zone load balancing enabled

### ISSUE THREAD

**Issue by phobologic** [remind101/empire#640]
http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-disable-crosszone-lb.html

ECS doesn't perfectly balance it's containers really, so this feature really needs to be enabled.

**Comment by benjamin-guillet** [comment]
Can close this now :) (unless you want to wait for the manual update)

**Comment by phobologic** [comment]
The PR isn't merged yet :)

**Comment by benjamin-guillet** [comment]
:see_no_evil:
