### ISSUE TITLE
Heroku API token

### ISSUE THREAD

**Issue by gileze33** [remind101/empire#646]
You guys mentioned the empire management API replicates the Heroku API - I built an in-house iOS app for managing our heroku apps (restart, scale etc) that I'm missing since I moved to empire.

To avoid building the 2FA login flow, I ended up using the account-wide API token that Heroku give you as authentication - is such a thing possible in empire? If it is, I figure I can probably just update the API endpoint but I'm struggling to work out where I would look for such a thing.

If that's not built in yet, where is the auth token from the emp client stored?

**Comment by gileze33** [comment]
Managed to find the `.netrc` file, but the following request doesn't seem to work :(

`curl https://empire-url/apps -H "Accept: application/vnd.heroku+json; version=3" -H "Authorization: Bearer password-value-from-netrc-file"`

Note that the same request using hostname api.heroku.com with the 'password' value for heroku from my `.netrc` seems to work fine

**Comment by ejholmes** [comment]
Hey @gileze33, you should be able to use the token from the `.netrc` by supplying it as the basic auth password:

```
-H "Authorization: Basic <base64 encode ":<token">
```

See https://github.com/remind101/empire/blob/c8469c424b3f58ecac86440575627c52ba25d299/server/heroku/authentication.go#L67-L74.

Let me know if that doesn't work for you!
