### ISSUE TITLE
Certificate Chain Support

### ISSUE THREAD

**Issue by kamkudla** [remind101/empire#654]
Hi guys,
I'm having this issue in that I need to have the certificate chain built in to the load balancer. I don't see a param in `emp ssl-cert-add`. When I manually add the certs to the ELB all is well, but then the empire doesn't allow me to do any deployment to the app because the ELB doesn't match the way it was initially configured. Confused as to how to set this up properly or if intermediary cert chain is not supported in empire.

**Comment by ejholmes** [comment]
Short Answer: I don't believe this is supported right now.

Long Answer: I think you could initially use `emp` to setup the app and load balancer, then use the AWS CLI to upload the correct cert and certificate chain using the same certificate name. I'm actually not sure if IAM let's you change an existing cert or if you have to delete it first, but as long as it's the same name as the one that was uploaded via emp, it should work. The cert name within IAM should be the [app id](https://github.com/remind101/empire/blob/master/ssl.go#L77), which you can find from `emp info -a <app>`.

Let me know if that works out for you!

**Comment by rgabo** [comment]
You should just include the whole certificate chain in the .crt along with
your certificate. We had the same problem, included the intermediate
certificate in the same CRT file that had only our issued certificate.
Works like the charm and emp will happily create the ELB correctly.

That being said, we've bumped into IAM limits even though our limit is
double the default (40 certificates per account). Any chance to have hashed
certificate names implemented so they get reused?

**Comment by phobologic** [comment]
^^ what @rgabo said.  Have you tried including the certificate chain in your certificate @kamkudla?  That should work/be supported.

**Comment by kamkudla** [comment]
@ejholmes Seems like `emp info` is broken for me I get `error: Unexpected error: 404 Not Found` for all apps even ones that are live and freshly set up. I was only able to get the certificate name via ELB AWS page. Didn't get around to trying to overwrite the cert. I went with what @rgabo suggested and it worked like a charm. Works great, thanks.

**Comment by kamkudla** [comment]
We should most definitely document this in the setup in the meantime while we extend the method to accompany the certificate chain in the upload

**Comment by phobologic** [comment]
@kamkudla `emp info` should work - it's working in our environment.  What version of empire are you running/how did you set it up?

**Comment by benguillet** [comment]
Yeah, it seems like emp is just not finding the API endpoint, thus returning a 404. Updating empire should fix it :).

**Comment by kamkudla** [comment]
@phobologic @benguillet Looks like I'm using version 0.9.1. 
I pulled it with `go get -u github.com/remind101/emp'.

**Comment by phobologic** [comment]
Sorry - I mean what version of empire?  How did you create your empire environment?  This isn't likely an `emp` CLI problem.

**Comment by kamkudla** [comment]
@phobologic stacker was used to set up the stacks. Regarding empire, not sure if the latest empire env was used. How could I check? Through empire API?

**Comment by phobologic** [comment]
Cool - can you give me the `mappings:` section from the empire.yaml that you used?  Or, alternatively, if you could give me the AMI that your controllers are using that'd work too.

Also the region you are running empire in, thanks!

Updating Empire with stacker usually means doing a stacker update with a new AMI, then killing each controller/minion host one at a time, allowing Autoscaling to update it.  I can give you more info about that if it turns out you need to update.

**Comment by kamkudla** [comment]
Sure thing. Here's the `mappings:` from from my empire.yml
```mappings:
  AmiMap:
    us-east-1:
      NAT: ami-c02b04a8
      ubuntu1404: ami-c135f3aa
      empire: ami-3186585a
    us-west-1:
      NAT: ami-67a54423
      ubuntu1404: ami-bf3dccfb
      empire: ami-2fd5286b
    us-west-2:
      NAT: ami-75ae8245
      ubuntu1404: ami-f15b5dc1
      empire: ami-85ede7b5
      ecs: ami-abf4fd9b 
```
Controllers are using `ami-85ede7b5` and the minions are using `ami-abf4fd9b` which is a custom image that contains logsprout and datadog integrated

**Comment by kamkudla** [comment]
Any ideas, guys?

**Comment by phobologic** [comment]
Sorry, haven't had a chance to look at this today - I'll try to get some time in a bit.

**Comment by kamkudla** [comment]
Thanks @phobologic. Looking forward. I do believe I may be running an old image.

**Comment by phobologic** [comment]
Hmm - so `ami-85ede7b5` is the latest AMI in us-west-2... and yeah, emp info came later!  Can you go ahead and open a bug/request in empire_ami to get a new one spun?  I'll make that happen ASAP - I need to revisit the current code in that repo anyway to see if I can get docker 1.8.1 running or if I should roll back to 1.7.0 entirely (there is a weird networking bug in 1.8.1 that I found after starting to roll it out).

I'm going to go ahead and close this bug for now so we can continue any conversation in the right place.  Thanks for the info @kamkudla
