### ISSUE TITLE
Stacker AMI for Empire

### ISSUE THREAD

**Issue by corentone** [remind101/empire#655]
Hello,
I am using remind101/stacker to bring up Empire with an ideal configuration.
Stacker has an AMI registered for Empire as part of conf/empire/empire.yaml

I found that the image is from August 12 (us-east-1 Empire PaaS 2015-08-12T22-32-58Z ami-1963c872) is not the latest. There is a new image from September 8th (Empire PaaS 2015-09-08T21-05-51Z ami-ffe58a9a).

I am assuming the AMIs are related to the recent Empire releases. Is this assumption correct?
Would it be possible  to add the AMI identifiers to Empire release notes and if any change is required to update as part of the release note?

I understand if stacker is not updated everytime if the update is backward compatible. I'm also going to have a look at remind101/empire_ami.

Thanks!
Co

**Comment by phobologic** [comment]
Hey @corentone - can you look at the account owner of the AMI you're seeing?  I'm wondering if someone else is using the packer file in empire_ami without modification, so they're producing images that are public as well.  The latest image we've built in the official empire_ami repo, for us-east-1, was actually from August 27th (`ami-dda318b6`).  That said, we haven't rolled that image out yet because we've run into issues with docker 1.8.1 in our environment, and that's what was pulled in in that image.  I haven't yet had a chance to go back and troubleshoot those issues. (see: https://github.com/docker/docker/issues/13914)

As of now I'd stick with `ami-dda318b6`.  Still curious where that new Empire PaaS image is from :)

**Comment by corentone** [comment]
Thanks @phobologic !
Here is what I get (only the two last results of the request):
```
ami-1963c872 897883143566/Empire PaaS 2015-08-12T22-32-58Z
ami-ffe58a9a 487220619225/Empire PaaS 2015-09-08T21-05-51Z
```
So I'm assuming `897883143566` is you/remind and `487220619225` is our mysterious owner.

Our mysterious owner (48..) posted a couple images `Empire PaaS 2015-08-01T01-29-43Z`, `Empire PaaS 2015-08-01T07-51-18Z`, `Empire PaaS 2015-08-02T21-08-21Z`. 
Earlier, we also have another unknown `427009882155/Empire Image 2015-07-22T05-08-08Z`, which posted 3 images on July 22nd.

https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:visibility=public-images;search=Empire;sort=name

Thanks for looking at it at the new AMI! I am looking forward to using new features of Empire (especially the `emp deploy -a X IMG`). For now, I'm going to follow your advice and stick to `ami-1963c872`.

**Comment by corentone** [comment]
@phobologic Any luck with the image?

**Comment by phobologic** [comment]
Sorry - been busy w/ work stuff.  I'll try to dive into this soon.

**Comment by corentone** [comment]
No worry! Thanks for the answer!

**Comment by phobologic** [comment]
@corentone I'm back from re:Invent and working today on some updates to the empire_ami - you a couple of pull requests are going into it today.

https://github.com/remind101/empire_ami/pull/6

**Comment by corentone** [comment]
Thanks @phobologic !

I hope re:Invent was nice!

**Comment by phobologic** [comment]
The new AMI is built and available in the github repo of stacker.  I have not spun a new stacker release, because I'm hoping to get some folks to play with it before I go forward.

For more info, check out: https://github.com/remind101/stacker/issues/97#issuecomment-147550523

**Comment by corentone** [comment]
Oops I forgot to update it.

The new AMI works great for me. I had a hiccup when my controllers would not stay up anymore and the ELB not forwarding to them (if you have pointers on how to debug it, that would be nice). I assumed that was because of the non-official update (with the non-official AMIs) I had on it and since I needed to tear down this stack, I didn't try much to debug it but just FYI.
My other stacks took the upgrade nicely :)

Thanks again!
