### ISSUE TITLE
GitLab/GitLab-CI in cluster

### ISSUE THREAD

**Issue by kamkudla** [remind101/empire#656]
Loving the support from the Remind folks here. Continue the awesome work. Would love some guidance from everyone here on how to proceed with:

So I've recently decided I want to move my repos to GitLab by self-hosting. I'm hosting code on GitHub right now - and for CI I've got set up Drone (drone.io) on an EC2 instance that's exposed to the public inside my VPC set up by Empire. There's a webhook that feeds to the drone instance, which spins up a container and starts running tests. I need to be able to perform docker containerization in order to spin up my services and run integration/functional tests. I think drone can handle it though set up is really buggy because it's still alpha. 

I see that GitLab offers a ton of awesome features and I would love to self-host this along with having GitLabCI integrated in so they work alongside one another. I was able to spin up a local test instance of GitLab dockerized with docker-compose (https://github.com/sameersbn/docker-gitlab). There's also images for GitLabCI and GitLab runners which I can spin up the same way (https://github.com/sameersbn/docker-gitlab-ci). 

I'm wondering how I could set this up with the empire cluster - or even if I should. What about data persistence and setting up the GitLabCI runners as workers?

**Comment by phobologic** [comment]
@kamkudla Empire is really meant for stateless 12 factor apps.  We don't suggest you setup anything stateful in Empire, as it really has no method of persisting data.

For persistent data services we tend to either use third party services (github, redislabs, etc) or we build them directly via cloudformation/stacker (rds, ec2 instances running rabbitMQ, etc).
