### ISSUE TITLE
Deregister Task Definitions when app is destroyed

### ISSUE THREAD

**Issue by ianneub** [remind101/empire#665]
Minor feature request: It would be nice if all the previous Task Definitions were deregistered when an app is destroyed.

As far as I can tell after destroying an app all the old Task Definitions are left lying around.

_Side note: Nice work so far. Thanks for open sourcing this!_

**Comment by bmarini** [comment]
Hey @ianneub, yeah that's a good call. We should be cleaning up those task definitions.
