### ISSUE TITLE
How to view previous logs after having enabled logspout-kinesis?

### ISSUE THREAD

**Issue by crohr** [remind101/empire#666]
I've managed to modify and configure the empire AMI to start a logspout-kinesis container when the instance boots, and then successfully using `emp logs` to look at the logs in realtime. That's already quite cool, but I've been forced to go back to using "classic" logspout + ELK stack because currently there is no way to go back in time (even just a little), which means any logs sent before running `emp logs` are not displayed. Is there anything I've missed? How do you handle this on your side?

Thanks for the awesome project!

**Comment by phobologic** [comment]
I do not believe this is currently possible - but definitely a great idea as a feature request.  Right now we'd only be able to show the last 24 hours of log entries - but after the Kinesis update it should be able to go up to 7 days.  Not sure if there's anything else we need to change to enable 7 days worth of back logs.  Thanks for the suggestion!

**Comment by benguillet** [comment]
Hey @crohr (salut), you're right, at the moment there is no mean to access older logs. To circuvent this we run two adapters on our logspout in parallel, essentially the kinesis and a sumologic one. We then use sumologic to retrieve and search older logs.

**Comment by crohr** [comment]
Salut @benguillet, thanks for the reply! I thought you would have some kind of subscriber to your kinesis streams, but it's even easier to ship logs twice to two different backends. I'll try that!

**Comment by ejholmes** [comment]
Going to close this one out.

**Comment by ejholmes** [comment]
Closed this one in error! We should still do this at some point.

**Comment by mhahn** [comment]
@crohr kinesis added support for this and so did empire!

https://github.com/remind101/empire/pull/830

one note is that the default retention period for a stream is 24 hours, you can increase this to up to 7 days (there are increased charges associated with this).

https://github.com/remind101/empire/issues/858 is opened to support setting that retention period within empire
