### ISSUE TITLE
Logs are disabled 

### ISSUE THREAD

**Issue by JacopoDaeli** [remind101/empire#667]
Hello everyone,
after installed the acme-inc:latest image, when I try to `emp log -a acme-inc`, I get `Logs are disabled`.

```
~ $ emp log -a acme-inc
Logs are disabled
```

By the way, if I ssh into the EC2 instance and I run `docker logs <container_id>` there are some logs.

Can someone help?

**Comment by crohr** [comment]
@JacopoDaeli as far as I understand it's still a feature that needs a bit of work (#666). Though you can already enable it if you build you own version of the empire_ami to include a logspout container that streams logs to kinesis, but I would wait for an official "use that feature, it's ready" for that.

**Comment by JacopoDaeli** [comment]
Thanks @crohr.

**Comment by phobologic** [comment]
Yep - I'm in the process of building a new Empire AMI today.  Should have a few different updates - including streaming logs.

**Comment by JacopoDaeli** [comment]
Awesome @phobologic

**Comment by phobologic** [comment]
Hey @JacopoDaeli - I've created a new AMI and updated stacker to use it.  The new AMI should include log streaming.

https://github.com/remind101/stacker/issues/97

The demo environment hasn't been setup for log streaming - I'll open an issue to track that.

**Comment by JacopoDaeli** [comment]
Awesome @phobologic

**Comment by JacopoDaeli** [comment]
@phobologic can you tell me what the new `ami id` ?

**Comment by phobologic** [comment]
https://github.com/remind101/stacker/blob/master/conf/empire/empire.yaml#L42

That said, you can't use that AMI with the cloudformation script - you'll need to use stacker, or manually provide the right user data to the instance when you launch it to get it working

**Comment by JacopoDaeli** [comment]
@phobologic I built a new cloud formation script using the new image `ami-8fbaf1ea` instead of the `ami-5943023c` and I pass `EMPIRE_LOG_STREAMER=kinesis` via the user data but it's not working. Not sure why. Should I do something else?

**Comment by phobologic** [comment]
What did you base your cloudformation script on?  Is it based on the plain cloudformation.json that we use for the demo environment?  That doesn't actually use the new AMI - the demo environment uses the plain ECS AMI, so it's missing a bunch of the features that the empire ami brings in.

To use the empire AMI you either need to use stacker (https://github.com/remind101/stacker/tree/master/conf/empire) which will handle a bunch of stuff for you, or you'll need to come up with a cloudformation.json that includes all of the variables that the ami expects in the userdata (which writes to a seed file) - see the README here: https://github.com/remind101/empire_ami

**Comment by JacopoDaeli** [comment]
Hey @phobologic I used a custom version of the cloudformation.json... I guess something is wrong. By the way I am now using stacker. I'll test it and I will let you know ASAP. Thanks for your help. 

Anyway, can you suggest me how can use `deploy` within `empire` at the best?

**Comment by phobologic** [comment]
By `deploy` do you mean https://github.com/remind101/deploy ?  Or just `emp deploy`?

**Comment by JacopoDaeli** [comment]
@phobologic I mean `https://github.com/remind101/deploy `. We would love to use `GitHub`, `DockerHub` within `Empire` for achieving `12-factor apps`.

**Comment by JacopoDaeli** [comment]
@phobologic very clever `stacker ` for generating an `empire` production env.
It works very nice, by the way my GitHub login doesn't work anymore. I get:

```sh
bin $ emp login
Enter email: myemail@gmail.com
Enter password:
error: Post https://api.github.com/authorizations: dial tcp 192.30.252.125:443: i/o timeout
```

Also could you me explain for what the generated `Nat01` and `Nat02` are generated for? I see the point of the `bastion`of course but that two instances I don't have idea how to use them.

Thanks a lot for your help,
Jacopo

**Comment by JacopoDaeli** [comment]
@phobologic all good with `stacker

**Comment by phobologic** [comment]
Hey @JacopoDaeli - so one issue with the current stacker setup is that it doesn't have the necessary stuff to get `deploy` working.  I'm going to be working on that this weekend.

Glad to hear the rest of it is working out for you!

As far as multiple environments, the way we do it (and it works well for us) is to setup aliases for each environment.  IE:

```
alias emp-staging="EMPIRE_API_URL=https://empire.stagingdomain.com/ emp $*"
```

**Comment by JacopoDaeli** [comment]
@phobologic correct I tried `deploy` with the current stacker setup but it doesn't work. Probably because of the issue you found, but I was also thinking because my github organization `imperodesign` as a different name from the docker one `impero`?

So when I deploy `deploy imperodesign/impero-inc` is actually trying to deploy ` imperdesign/impero-inc ` instead ` impero/impero-inc ` ?

**Comment by phobologic** [comment]
The reason it's not working is because for deploy to work you need to have github send a webhook from your repo (for deployments) to the Empire API.  Right now the Empire API is limited to only be accessed from a single IP range.  I need to make it so you can allow Github's IP range to be able to hit it as well.

I actually haven't dealt much w/ the `deploy` command - but @ejholmes should be able to give you some guidance here.

Glad the logging stuff is working for you - we were really excited to get it out there!

**Comment by JacopoDaeli** [comment]
I see. I can allow GitHub's IP range manually for the moment. wait for some guidance from @ejholmes .

**Comment by ejholmes** [comment]
@JacopoDaeli If you can rename the docker org to match your github org, that's probably the easiest and least surprising way to enable GitHub Deployments. If you can't, you can set the [`EMPIRE_GITHUB_DEPLOYMENTS_IMAGE_TEMPLATE`](https://github.com/remind101/empire/blob/master/docs/configuration.md) variable, to a Go text/template that will return the correct docker image. The default value is `{{ .Repository.FullName }}:{{ .Deployment.Sha }}`.
