### ISSUE TITLE
Support tarball slugs

### ISSUE THREAD

**Issue by protomouse** [remind101/empire#685]
We're considering Empire (thanks, guys!) and I think it would be useful if it could support Heroku-like tarball slugs in addition to image-based deploys. We're currently using Flynn's [slugbuilder](https://github.com/flynn/flynn/tree/master/slugbuilder)/[slugrunner](https://github.com/flynn/flynn/tree/master/slugrunner) to remove the need for a privately hosted Docker registry, in favour of just putting blobs on VPC-private S3.

I imagine something like:

    emp deploy https://drillbucket.s3.amazonaws.com/apps/acme-inc/acme-inc.sha.tgz

In this mode of operation, container definitions change on two accounts. The first is of course the image, which is the slug runner itself. The second is the addition of an environment variable that points to the blob (flynn/slugrunner uses `SLUG_URL`), which the runner will consume.

Does this make sense for Empire? It's not the kind of change we're keen on maintaining in a fork, so I'm querying interest to see this added to Empire proper (and spec things out a bit).

**Comment by ejholmes** [comment]
While I like the idea, this would be a substantial change for Empire to support. ECS currently only works with the docker registry, and that would probably be the most substantial change required.

Within Empire itself, we'd need to decouple slugs from the [Image](https://github.com/remind101/empire/blob/master/pkg/image/image.go#L33-L45) type so that a URL could be used to satisfy a slug.

**Comment by protomouse** [comment]
Yeah. With Amazon ECR on the horizon, I think having a reliable and scalable Docker registry solution within VPC confines will no longer be a burden - which is what this use case ultimately boils down to. That may be something to consider also. Right now, concrete action is still contingent on a few key internal decisions for us. In the meantime, I'm open for more +1s.

**Comment by phobologic** [comment]
What would be your proposal for replacing ECS in this case?  Or would you try and implement this by updating the ECS agent (not even sure this would be possible, since AWS's service would have to allow it as well).

**Comment by protomouse** [comment]
I'll go ahead and close this for the time being, as we will most likely end up with a private registry for caching Docker Hub anyway. @phobologic it would have to be a refactoring of Empire core, as @ejholmes described it.
