### ISSUE TITLE
Weird issue with emp ps

### ISSUE THREAD

**Issue by gileze33** [remind101/empire#699]
Hey,

I must be doing something stupid here - I've updated the empire agent running on the controllers, but no emp ps is giving me a `NoCredentialProviders` error (see logs below).

The role attached to the controller definitely allows `ecs:List*` and I'm completely flumoxed as to why only `emp ps` doesn't work, yet all the other commands do.

`t=2015-12-16T22:05:40+0000 lvl=info msg=ListServicesPages request_id=7fd069b6-3267-4751-b267-ccad75a00a63 trace.id=4503e879-e830-430b-8b0a-cbb930316402 trace.parent= trace.func=github.com/remind101/empire/pkg/ecsutil.(*ecsClient).ListServicesPages trace.file=/go/src/github.com/remind101/empire/pkg/ecsutil/ecs.go trace.line=92 trace.duration=975.751µs
t=2015-12-16T22:05:40+0000 lvl=eror msg= request_id=7fd069b6-3267-4751-b267-ccad75a00a63 error="\"NoCredentialProviders: no valid providers in chain\"" line=94 file=/go/src/github.com/remind101/empire/pkg/ecsutil/ecs.go
t=2015-12-16T22:05:40+0000 lvl=info msg=request.complete request_id=7fd069b6-3267-4751-b267-ccad75a00a63 status=500`

Is there potentially something obvious I'm missing?

Cheers
Giles

**Comment by phobologic** [comment]
What did you update the empire daemon to?

**Comment by gileze33** [comment]
I updated the AMI in the launch config to `ami-3cef374f` - latest version built in circleci for `eu-west-1`

**Comment by gileze33** [comment]
Is there any way to get a more details message out in the logs? I'm not remotely familiar with `go` and it's logging

**Comment by gileze33** [comment]
So now I feel dumb... I lost the IAM role in the new launch config :( Sorry!
