### ISSUE TITLE
Add support for Amazon ECR

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#703]
How we pass a docker.AuthConfiguration down for pulls should be abstract a bit so that we can generate a docker.AuthConfiguration dynamically to work with ECR, and we can provide various AuthConfigurationProvider implementations:

```go
// Generates a docker.AuthConfiguration from a .dockercfg
FileProvider(file io.Reader) docker.AuthConfiguration {}
// Generates a docker.AuthConfiguration for an Amazon ECR registry.
ECRProvider() docker.AuthConfiguration {}
// Merges multiple docker.AuthConfigurations together.
MultiProvider(providers ...AuthConfigurationProvider) AuthConfigurationProvider
```

**Comment by protomouse** [comment]
FWIW, I took a stab at this today: wowgroup/empire@14bee7db

**Comment by ejholmes** [comment]
@protomouse awesome stuff. If you wanna open a PR, I'd love to get this merged in for the next release.

**Comment by protomouse** [comment]
PR done.

**Comment by JacopoDaeli** [comment]
@ejholmes @protomouse how can we use ECR with EMPIRE ?

**Comment by ejholmes** [comment]
https://github.com/remind101/empire/pull/730 was just merged and will be in the next release.

@JacopoDaeli The only thing you should need to do is add the following permissions to your EC2 container instances instance profile: 

```
ecr:GetAuthorizationToken
ecr:BatchCheckLayerAvailability
ecr:GetDownloadUrlForLayer
ecr:BatchGetImage
```
