### ISSUE TITLE
Need to stop using uuid from code.google.com

### ISSUE THREAD

**Issue by phobologic** [remind101/empire#718]
When installing the latest `emp` command:

```
# go get -u github.com/remind101/empire/cmd/emp
warning: code.google.com is shutting down; import path code.google.com/p/go-uuid/uuid will stop working
```

**Comment by benguillet** [comment]
note: this is only a problem is you haven't activated go1.5+ vendoring (`export GO15VENDOREXPERIMENT=1`)

**Comment by ejholmes** [comment]
I'll update the docs to be more explicit about requiring Go 1.5 and setting `GO15VENDOREXPERIMENT`.

**Comment by phobologic** [comment]
Ahh - ok, I was on 1.5, but hadn't set that variable, I'll add that to my env.
