### ISSUE TITLE
ECS error when attempting to deploy acme-inc demo

### ISSUE THREAD

**Issue by jjbohn** [remind101/empire#733]
Was going through the [Quickstart Guide](http://empire.readthedocs.org/en/latest/quickstart_using/#empire-using) and got the following error:

<img width="1018" alt="1__jjbohn_johns-macbook-pro____src_alphasights_empire_cmd_emp__zsh__and_empire_empire_test_go_at_c538cbcb16a34b04d0b6eaa05a30a03101112092_ _remind101_empire" src="https://cloud.githubusercontent.com/assets/401301/12467030/51c90876-bfa6-11e5-8a2a-b485a590b5ff.png">

**Comment by ejholmes** [comment]
Looks like this was caused by https://github.com/remind101/empire/pull/720. It's not in a release yet, so I'm going to go ahead and revert that change.

**Comment by ejholmes** [comment]
Just reverted that change. If you re-build the stack, everything should work normally. Thanks for letting us know!

**Comment by jjbohn** [comment]
@ejholmes Yup, that was it. Thanks!
