### ISSUE TITLE
emp run tries to pull from Docker Hub even though using Quay.io

### ISSUE THREAD

**Issue by shidenkai0** [remind101/empire#739]
Hi everyone,

I setup an empire cluster using stacker 0.6.0 with the latest blueprints, using Quay.io as registry, and managed to deploy my applications. Everything works properly except the emp run command, which tries to pull from docker hub, whereas my original deployment is from Quay.io. This results in the following:

```
runner: pull: Error: image username/repo:tag not found
```
Empire seems to be trying to pull from Docker Hub despite DOCKER_REGISTRY being set to Quay.io in the seed file.

Sincerely yours,

**Comment by ejholmes** [comment]
Good catch. I'm 99% positive this is caused [here] (https://github.com/remind101/empire/blob/master/pkg/runner/runner.go#L73-L77), which doesn't duplicate the logic [here](https://github.com/remind101/empire/blob/master/empire.go#L565-L578) (putting the registry portion in the `Repository` field). We should extract that into pkg dockerutil and re-use it for pulling.
