### ISSUE TITLE
Port appended to url when one is already set

### ISSUE THREAD

**Issue by jjbohn** [remind101/empire#743]
When running empire controller locally (using `docker-compose`), it appears that `:80` is being appended to the `EMPIRE_API_URL`. For example:

```
$ emp run -a acme-inc echo "Test"
error: dial tcp: too many colons in address 192.168.99.100:8080:80
```

If I launch the server on port 80 and change `EMPIRE_API_URL` to `192.168.99.100`, it works as expected.

**Comment by ejholmes** [comment]
This was actually fixed recently in https://github.com/remind101/empire/pull/741, but isn't in a new release yet. If you want the latest version that includes this, you can `go get -u github.com/remind101/empire/cmd/emp`
