### ISSUE TITLE
ECS AMI outdated

### ISSUE THREAD

**Issue by xiongchiamiov** [remind101/empire#748]
The ami specified in `docs/cloudformation.json` no longer exists, producing an ["AMI cannot be described" error](http://serverfault.com/a/708806/12214).  The current image for us-east-1, as listed in [the docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html
), is `cb2305a1`.

**Comment by ejholmes** [comment]
Thanks for the heads up. I'll update the cloudformation stack.

Looks like we can probably automate this to some extent and at least fail CI if the image isn't the latest version. This gives me the most recent ECS AMI version:

```console
aws ec2 describe-images \
  --filters Name=name,Values='amzn-ami-2015.09.e-amazon-ecs-optimized*' \
  --owners aws-marketplace \
  --region us-east-1 \
  --output text \
  --query 'Images[0].ImageId'
```
