### ISSUE TITLE
md5sum location disparity

### ISSUE THREAD

**Issue by xiongchiamiov** [remind101/empire#749]
`bin/bootstrap` checks to see if `/usr/bin/md5sum` exists, and if it does, instead tries to use `/usr/sbin/md5sum`.  These should be the same path, probably the former, or the path to the binary shouldn't be relied on and the `PATH` should be consulted.

**Comment by phobologic** [comment]
https://github.com/remind101/empire/pull/752 for this as well.  Thanks.
