### ISSUE TITLE
Bootstrap script doesn't quote keypair

### ISSUE THREAD

**Issue by xiongchiamiov** [remind101/empire#750]
If you try to enter a keypair name that has a space in it, the bootstrap script complains:

    AWS SSH KeyName: Test Server
    Do you have a docker account & want to use it for private repo access? [y/N] 
    ==> Launching empire in AZs: us-east-1a us-east-1b, Cloudformation Stack empire-f49c73cf
    
    Error parsing parameter '--parameters': Expected: '=', received: 'EOF' for input:
    Server
          ^

Manually quoting this as `'Test Server'` works as you'd expect, but the script should [quote](http://mywiki.wooledge.org/Quotes) appropriately.

**Comment by phobologic** [comment]
Good catch, simple fix - https://github.com/remind101/empire/pull/752
