### ISSUE TITLE
Verify that aws-sdk-go is retrying throttling errors

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#751]
We see ThrottlingException's pretty frequently when running `emp ps`. The aws clients should be retrying this with backoff, so the fact that we're still seeing this makes me question if it's actually retrying.

```console
$ emp ps 
error: ThrottlingException: Rate exceeded
    status code: 400, request id: 4e339002-c9df-11e5-97c0-d708bdd78d89
```

**Comment by ejholmes** [comment]
Definitely looks like it's retrying, but the default retry limit is [3 retries](https://github.com/aws/aws-sdk-go/blob/9d7bc2d6ca2ada0468f705f0e9725ca97f8550c8/aws/client/client.go#L54) and with the algorithm in the [default retrier](https://github.com/aws/aws-sdk-go/blob/9d7bc2d6ca2ada0468f705f0e9725ca97f8550c8/aws/client/default_retryer.go#L34-L37), this will retry over the course of about 500ms, so it's still pretty easy to hit throttling while retrying.

Maybe the best workaround would be to initially bump this up to something like 6 (retry 6 times over ~5 seconds)? It means that `emp ps` and `emp deploy` would be slower for apps with big Procfiles, but atleast it wouldn't return an error.

For future reference, reproduced these using this go program:

```go
package main

import (
	"log"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/ecs"
)

const concurrent int = 150

var client *ecs.ECS

func main() {
	config := &aws.Config{MaxRetries: aws.Int(15)}
	config.WithLogLevel(aws.LogDebugWithRequestRetries)
	client = ecs.New(session.New(config))

	var i int
	for {
		i++
		if err := get(); err != nil {
			log.Fatal(err)
		}
	}
}

func get() error {
	errCh := make(chan error, concurrent)

	for i := 0; i < concurrent; i++ {
		go func() {
			_, err := client.DescribeTaskDefinition(&ecs.DescribeTaskDefinitionInput{
				TaskDefinition: aws.String("047bc51a-8d16-4dba-97f9-43f53e22f008--web"),
			})
			errCh <- err
		}()
	}

	for i := 0; i < concurrent; i++ {
		err := <-errCh
		if err != nil {
			return err
		}
	}

	return nil
}
```

**Comment by ejholmes** [comment]
Another thing to take note, this is less of a problem if you're using separate AWS accounts per Empire environment, since the rate limit is per account.

**Comment by nzoschke** [comment]
Thanks for reporting this in the open, convox is seeing it too. Do you have a patch that fixes it?

**Comment by ejholmes** [comment]
Not at the moment. This may end up being a wontfix for us until we have a better way to solve it. This is mostly a problem because we create separate task definitions for every process defined in the Procfile. The only thing that differs between the task definitions is the command, environment, and labels. If ECS services end up supporting all of these as overrides, then we could just use a single task definition for all processes in the app, which would most likely solve all of the throttling issues and also help a lot with performance.

**Comment by phobologic** [comment]
:+1: for at least upping the # of retries.  Maybe it'd be worth using a different retryer as well that's a bit less aggressive.  That said, yeah, these are all band-aids. I don't think there's much we can do to fix it.

**Comment by ejholmes** [comment]
I think we can go ahead and close this now that #781 was merged.
