### ISSUE TITLE
Invalid link in README.md

### ISSUE THREAD

**Issue by stavro** [remind101/empire#754]
The link provided in the README.md does not work.

From README:
```
$ curl -L https://github.com/remind101/empire/releases/download/latest/emp-`uname -s`-`uname -m`  > /usr/local/bin/emp
```

ex: `https://github.com/remind101/empire/releases/download/latest/emp-Darwin-x86_64` is not a valid release. The `latest` version tag cannot be used in this way

**Comment by ejholmes** [comment]
That's disappointing :(. Read me now points to the latest version.
