### ISSUE TITLE
deploying acme-inc requires authentication

### ISSUE THREAD

**Issue by cyommer** [remind101/empire#766]
I'm getting the following when trying to emp deploy remind101/acme-inc:latest:

`$ emp deploy remind101/acme-inc:latest`
`Pulling repository remind101/acme-inc`
`error: Authentication is required.`

The debug version of that:

`d9`
`{"status":"Pulling repository remind101/acme-inc"}`
`{"errorDetail":{"message":"Authentication is required."},"error":"Authentication is required."}`
`{"errorDetail":{"message":"no such image"},"error":"no such image"}`

`0`

`Pulling repository remind101/acme-inc`
`error: Authentication is required.`

I can pull the image from the docker cli without issue, so it doesn't appear to be a docker api issue.   I'm using v0.10.0 of the client.  Am I missing something?

**Comment by ejholmes** [comment]
@cyommer that's pretty strange. The remind101/acme-inc repository on Docker Hub is [public](https://hub.docker.com/r/remind101/acme-inc/). What happens when you `docker pull remind101/acme-inc`? What version of Docker are you using?

As a side note, I've seen this message returned before when Docker Hub is having API issues.

**Comment by cyommer** [comment]
@ejholmes Sorry - I mean to mention that I can docker pull that (or any other) image without an issue.  It's only when I do it through the emp command line that things go south.   I upgraded the docker-engine version on the controllers and the minions to 1.10.3, and now I get this message:

`error: API error (500): Get https://registry-1.docker.io/v2/remind101/acme-inc/manifests/latest: unknown: too many failed login attempts for username or IP address'

Which doesn't seem to make sense.  I thought it may have something to do with the AMI I'm using (ami-80166fea), but, again, I'm not sure why that would be.   Still investigating.

**Comment by cyommer** [comment]
@ejholmes Closing.  Seems to be a PEBKAC error.  I was using an organization name as the docker_registry_user, and it appears that was causing the issue.  When I changed that and updated it through stacker, everything seems to be pulling.   Was a careless oversight on my part and a setting about which I completely forgot.  Sorry for any lost cycles.  Feel free to curse me Yosemite Sam style.
