### ISSUE TITLE
Application can get stuck trying to run a process that doesn't exist

### ISSUE THREAD

**Issue by gileze33** [remind101/empire#777]
An engineer in our team tried to scale web=1 in our staging cluster a few days ago, and despite getting the error message about invalid usage, that app is now stuck trying to create the `web` task despite only `worker` existing in our `Procfile`.

Things attempted to delete / re-create:
 * Deleted the app in empire, re-created, deployed new docker image tag
 * Completely removed all instances in the ECS cluster (minions and controllers) and allowed them to be re-created
 * Re-named the entire project, including docker image name (just in case any artifacts were left around linked to the name `notify`)

I'm now at a total loss as to what's going on. I can't find anywhere where it has any artifacts remaining in postgres for the app.. Maybe you guys could help point me in the right direction?

**Comment by ejholmes** [comment]
Hey @gileze33. Since you closed this, I'm assuming figured it out. If not, could you clarify what "stuck" means here? Is the ECS service still around (it would be named after the app id, `emp info -a <app>` with `--web` appended)?
