### ISSUE TITLE
Investigate security policy for SSL ELBs

### ISSUE THREAD

**Issue by phobologic** [remind101/empire#797]
Trusted advisor is showing that one of our Empire generated SSL ELBs uses a `outdated predefined SSL security policy`.  Should dig into this and figure out what changes should be made.

**Comment by ejholmes** [comment]
I ran trusted advisor against a new ELB created with the CloudFormation backend and it didn't report anything, so we can probably close this.

**Comment by phobologic** [comment]
Sounds good - especially since we'll get all new ELBs.
