### ISSUE TITLE
Switch to pkg/errors?

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#812]
http://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully is a good read on the issues with error handling in Go, and hits on a lot of pain points that we've had with error handling inside Empire.

We currently rely on `pkg/reporter` calls at the source of errors to get reasonable stack traces, but this sucks for multiple reasons:

1. If the error continues down the stack and there's another call to reporter.Report, that error is getting reported twice.
2. It feels wrong to be putting error reporting anywhere other than at the very top of the stack. This results in some errors getting reported, that are gracefully handled further down the stack (e.g. when we use the error returned from UpdateService to check if the service already exists).
3. Currently requires adding context.Context support, which most Go packages don't support.

If we use pkg/errors, then any errors bubbled up can be reported and still have a sane stack trace that we can actually use to debug the issue.

**Comment by phobologic** [comment]
👍 +somany

**Comment by ejholmes** [comment]
I'm gonna close this. `pkg/errors` has it's own set of problems, but we've been annotating errors with more information so they're easier to track down, which I think solves this for the most part.
