### ISSUE TITLE
"unexpected end of JSON input"

### ISSUE THREAD

**Issue by uptownhr** [remind101/empire#817]
Hi,

When starting empire with `docker-compose up`, the empire_server_1 exits with the last stdout message being, `unexpected end of JSON input`. 

1. git clone
2. docker-compose up
3. Wait for containers to start
4. notice empire_server_1 dies with error

**Comment by mhahn** [comment]
if you're on master, you'l see something like this right now:
```
$ docker-compose up
Starting empire_postgres_1
Starting empire_server_1
Attaching to empire_postgres_1, empire_server_1
postgres_1 | LOG:  database system was interrupted; last known up at 2016-05-03 20:44:30 UTC
postgres_1 | LOG:  database system was not properly shut down; automatic recovery in progress
postgres_1 | LOG:  invalid record length at 0/1888AE0
postgres_1 | LOG:  redo is not required
postgres_1 | LOG:  MultiXact member wraparound protections are now enabled
postgres_1 | LOG:  database system is ready to accept connections
postgres_1 | LOG:  autovacuum launcher started
server_1   | Up to date
server_1   | 2016/05/03 21:10:53 error validating CloudFormation template: CustomResourcesTopic is required
empire_server_1 exited with code 1
```

This is because the docker-compose file is setup to test the new cloudformation scheduler.

Within, `docker-compose.yml` change:
```
EMPIRE_SCHEDULER: cloudformation
```

to 

```
EMPIRE_SCHEDULER: ecs
```

does that help?

**Comment by ejholmes** [comment]
Hey @uptownhr. This happens because Empire tries to connect to postgres before the postgres container fully initializes the database and starts running. You can simply run `docker-compose up` again and it'll connect. Let me know if that helps.

**Comment by ejholmes** [comment]
Gonna close this for now. @uptownhr feel free to re-open if that doesn't fix the issue for you.
