### ISSUE TITLE
Events should be written to the apps log stream

### ISSUE THREAD

**Issue by mhahn** [remind101/empire#832]
When events are published, we should write them to the log stream

**Comment by mhahn** [comment]
@ejholmes to implement this:

- we can use: https://github.com/remind101/kinesis which only works if the stream exists
- or i was thinking we could replace the "writer" code within https://github.com/remind101/logspout-kinesis/ to use the above kinesis library and move the stream creation etc. to the kinesis library.

that way when an event is published (ie. create/deploy etc) and a stream doesn't exist, the same code is being called to create and write to the stream.

i was thinking if we pulled the kinesis code out of logspout-kinesis that would help us move away from logspout in the future, but if you switch to logstash, you would be using some ruby kinesis output plugin.

i see two options for tackling this:

1. use kinesis library to write to the stream with the app id, if the stream doesn't exist, just don't write the event.
2. refactor the stream creation process out of logspout-kinesis and into the kinesis library that will get called by both logspout-kinesis and empire.

1 is the faster implementation that i think makes the most sense. i don't think it matters if you drop some events from the stream, there is no guarantee that the DropWriter isn't going to do that either and the window of the stream not existing is small.

thoughts?

**Comment by phobologic** [comment]
I'm honestly open to either of them - the fact that logstash seems likely in our future now makes me wonder if this shouldn't just wait for that implementation.
