### ISSUE TITLE
Weird behavior when Procfile is missing

### ISSUE THREAD

**Issue by fbidu** [remind101/empire#860]
Hello,

Today I tried to push a Docker image and after several tries all I got was `EOF` errors. I double checked my `Dockerfile` and everything was okay. 

After a while I realized that there wasn't a `Procfile` in my project. I created one and the deploy worked. One last issue was that I wasn't able to delete the app associated with the former docker.

I think it should be nice to check the existence of the `Procfile` and display a nice warning and halt the deployment in case the file is missing.

**Comment by ejholmes** [comment]
Hey @fbidu. When a Procfile isn't provided, empire should default to a "web" process that uses the CMD directive from the Dockerfile. Couple questions:

* What version of Empire are you using?
* Did the Dockerfile specify a CMD?

**Comment by fbidu** [comment]
Yes, it did! `CMD [ "npm", "start" ]`. It is the latest one, I had just installed Empire at the time
