### ISSUE TITLE
Make rollback safer

### ISSUE THREAD

**Issue by ejholmes** [remind101/empire#881]
Right now, it's too easy to accidentally roll back to a really old release. Some ideas:

1. Only allow rolling back up to 10 releases (e.g. if you're on v1130, you can only roll back v1120-v1129).
2. Require confirmation when rolling back, and show a diff or something between the release versions.

**Comment by mhahn** [comment]
Asking for a confirmation if the release is greater than 10 releases ago makes sense. Not allowing someone to rollback to whatever version they want seems too restrictive. You could be setting a bunch of env vars or some other edge case.

We should be able to reuse some of the required commit message logic/code to do this

**Comment by Nosajool** [comment]
The way I'm thinking of doing this is to do the validation client side.

- Fetch current release version
- If rolling back farther than 10 versions: "You are rolling back x versions to v123. If you would like to continue, type v123"

**Comment by ejholmes** [comment]
👍 I think a pure client side solution for this is the right way to go.
