### ISSUE TITLE
'relation "processes" does not exist' after updating to 0.10.1

### ISSUE THREAD

**Issue by WheresWardy** [remind101/empire#890]
Today we attempted to upgrade our version of empire to 0.10.1 by modifying the task definition in ECS to use the new version of the tag. After this we updated our local version of the empire client to 0.10.1 as well.

When performing some actions, like `releases` for an app, we get the following error:
```
$ emp releases -a APP_NAME
error: pq: relation "processes" does not exist
```

And when trying to deploy to an existing app we get this:
```
error: pq: column "process_types" of relation "slugs" does not exist
```

So we rolled back to the previous version of empire in the task definition (0.10.0) but we're still getting the exact same errors from the client, so at the moment we can't use empire in any functional way. Do you know what could be going on here?

**Comment by ejholmes** [comment]
Hi @WheresWardy. Couple questions:

1. Did you run the migrations (`empire migrate` or set the --automigrate flag when running `empire server`)?
2. Rolling back should definitely not give you that error if you're indeed running 0.10.0. Can you post what's in the `schema_migrations` table?

**Comment by WheresWardy** [comment]
Resolved with help, thank you!

**Comment by ejholmes** [comment]
I think we could definitely do something here so that Empire doesn't run if the database schema doesn't match what it expects.

I'll open a separate issue for that.
