### ISSUE TITLE
emp destroy fails due to network

### ISSUE THREAD

**Issue by skorpios** [remind101/empire#920]
Hello,

Today I tried to delete an app that was created a couple of months ago and never really used:

```
$ emp destroy APPNAME
warning: This will destroy APPNAME and its add-ons. Please type "APPNAME" to continue:
> APPNAME
error: http: server closed connection
```

After I type `APPNAME`, it hangs for about 1 minute, then the error message appears before exiting.

I then tried to destroy another app and it went fine. The problem happens only with this specific app.

I am using version `0.10.1` of the client.

**Comment by phobologic** [comment]
Hey @skorpios - can you take a look at the empire daemon logs to see what is going on on the daemon side?  What version of the empire daemon are you running?  How did you set up the environment (did you roll your own setup?  use stacker? use the demo cloudformation template?)?

Thanks.

**Comment by skorpios** [comment]
Thanks for your answer @phobologic. The only related lines I can see in the daemon logs are:
```
t=2016-07-11T16:14:43+0000 lvl=info msg=request.start request_id=5f75626f-20f1-497a-b933-192c8c73c511 method=DELETE path=/apps/APPNAME
t=2016-07-11T16:14:43+0000 lvl=info msg=authenticated request_id=5f75626f-20f1-497a-b933-192c8c73c511 user=skorpios
```
These lines appear just after I type the name of the app in `emp destroy`. When `emp destroy` displays the error and exits, I can't see anything related in the logs of the daemon.

The daemon is at version `0.10.1` too, and we have our own setup.

One thing I noticed is that the ELB of the app doesn't have any EC2 instance. I'm not sure if this is due to `emp destroy` partially working, or the instance being manually removed earlier.

**Comment by phobologic** [comment]
When you do a `emp apps` does the app still show up?  Has Empire been upgraded since you deployed the app?  Do you know what version of Empire it was deployed under?  Had you tried migrating to the experimental cloudformation backend?

**Comment by skorpios** [comment]
Yes, `emp apps` is still showing the app. Empire has been upgraded since we created the app on the 4th of March. We were _probably_ using `0.10.0` at the time. We didn't try migrating to the experimental cloudformation backend, do you think we should?

**Comment by phobologic** [comment]
I wouldn't try and switch backends - that'll probably cause issues.  It's really strange that there are no other errors in the logs around the destroy - the error you got on the CLI comes from when a request takes more than the ELB timeout on the controllers (usually 60 seconds), though I can't imagine what might be taking it so long. Can you tell me more about the app?  How many entries in the `Procfile`?  How many configured processes?

One last thing - could you restart the empire daemon processes on all your hosts, and attempt it again?  Thanks!

**Comment by ejholmes** [comment]
I've seen this happen once before myself, and it was due to a database lock not being released. Can you post the output of `select * from pg_locks`?

Restarting the Empire daemon should cause all of the locks to be released and allow you to destroy the app.

**Comment by skorpios** [comment]
Thanks for your help. I stopped the daemon and I couldn't see any locks. When it started again, I queried the database for blocking processes and here was the output:
```
 blocked_pid | blocked_user | blocking_pid | blocking_user |               blocked_statement               | current_statement_in_blocking_process
-------------+--------------+--------------+---------------+-----------------------------------------------+---------------------------------------
        2636 | empire       |         2635 | empire        | UPDATE ports SET taken = NULL WHERE port = $1 | DELETE FROM "apps"  WHERE ("id" = $1)
```

**Comment by phobologic** [comment]
Do you only have a single empire daemon, or do you have multiple?  DId you restart all empire daemons?

First: Can you do `select * from pg_locks` on the database.
Second: If you see any locks, go ahead and shutdown all Empire daemons.

After that check the locks again, there shouldn't be any in theory.  Then try deleting the app again.

Thanks!

**Comment by skorpios** [comment]
Thanks all for your time. In fact, the issue was due to database locks. A `select * from pg_locks` was showing a steady number of locks (~150), and getting rid of all them solved the issue.

The blocking statements where mostly `UPDATE ports` and `DELETE FROM "apps"` statements (as shown in my previous comment), and the oldest ones started when the problem appeared.

I don't know what was the root cause, and I'm wondering if it would be possible to output a hint pointing to database locks in that particular case. I consider my problem being solved anyway :) Thanks!

**Comment by ejholmes** [comment]
@skorpios awesome, thanks for the update and glad the issue was resolved. It's hard to say what would have caused the lock without a repro.

Probably something that we should do is set some reasonable `statement_timeout`'s and `lock_timeout`'s when postgres connections are opened, so that statements can't lock up the database indefinitely like this.
