### ISSUE TITLE
Support providing a log level to empire

### ISSUE THREAD

**Issue by mhahn** [remind101/empire#929]
This would let us add more debug logging via `logger.Debug(ctx, ...)` and only enable these during dev or debugging.

**Comment by ejholmes** [comment]
Someone related, I'd love to do a revamp of logging. There's some places where we use the go logger (e.g. `cmd/empire`) and some places where we use `pkg/logger`. It'd also probably be good to remove the dependency on `pkg/logger` and bring it in as `remind101/empire/logger`.
