### ISSUE TITLE
emp env-load does not support multiline values

### ISSUE THREAD

**Issue by zbyte64** [remind101/empire#988]
Sometimes an environment value has a new line. When representing this in an env file the CLI is unable to properly parse a multiline expression where: 

```
AVAR='stuf
and
morestuf'
``` 

I came across this issue when attempting to move off heroku:
```
$ heroku config --app montage-dev -s > montage-dev.env
$ emp env-load -a montage montage-dev.env
error: poorly formatted environment: variable '-----END CERTIFICATE-----'' has white spaces
```

**Comment by zbyte64** [comment]
I've looked at https://github.com/joho/godotenv and they too don't read multilines but they do replace `\n` with an actual new line. While that isn't directly compatible with heroku's output, it does add a workable path forward.

Should we just use `github.com/joho/godotenv` for parsing env files? Let me know and I'll make a pull request & test.

**Comment by ejholmes** [comment]
Hey @zbyte64. Thanks for the report! godotenv definitely likes like a more complete implementation for parsing a .env file. Feel free to open a PR!

Out of curiousity, did you try using shell expansion and `emp set`. I _think_ that may work fine for multiline but not sure:

```console
emp set $(heroku config -s)
```

**Comment by zbyte64** [comment]
Attempting to use `emp set` results in the following error:

```
$ emp set -a montage $(heroku config -s -a montage-dev)
bad flag syntax: -----END
Usage: emp set [-a <app or remote>] [-m <message>] <name>=<value>...
Use 'emp help set' for more information.
error: bad flag syntax: -----END
```
